### ISSUE TITLE
Allow RuntimeImpl implementations to be provided as external .so file

### ISSUE THREAD

**Issue by sboeuf** [cri-o/cri-o#2255] opened 2019-04-15 02:07 UTC
In order to limit the amount of dependencies onto external repositories, we should be able to provide through `crio.conf` an implementation of a specific type of `RuntimeImpl` as a shared library (`.so` file).
A concrete example is the `runtime_vm.go` implementation, that could live inside https://github.com/kata-containers/runtime repository. A user that would like to use this implementation would provide the `runtime_vm.so` file provided by Kata Containers, given that it would specify the path from the `crio.conf` file.

**Comment by mrunalp** [comment] 2019-04-15 05:00
:+1:

**Comment by amshinde** [comment] 2019-07-15 17:48
@mrunalp An update on this issue.
I moved the implementation of runtime_vm.go to  https://github.com/kata-containers/runtime repository and  vendored  the `oci` package under crio into kata as the vm implementation requires data structures defined in this package. With this I had to resolve all the dependency conflicts between the transitive dependencies introduced by the vendoring of crio oci package and several other packages that it depends on.

With this I changed the crio.conf file to point to the plugin path instead. The crio code was modified to open the plugin and perform a lookup for the functions within this plugin as specified in the plugin api.
I ran into a couple of issues while doing so. First I saw this panic:
`panic: http: multiple registrations for /debug/request`.

You can see a similar issue here: https://jira.hyperledger.org/browse/FAB-12031
The issue seems to be a problem with `golang.org/x/net` package, which when vendored twice can cause this panic. crio includes this in its vendor directory and the newly created plugin ends up requiring this vendor as well, so while opening this plugin, you see the above error.
To test it out, I simply deleted the package from `vendor` directory from crio repo and this seems to resolve the panic seen while opening the plugin.

We do need to find a workable solution for this though. Looking at the crio repo I see that it uses go modules, so was wondering why crio includes the `vendor` dir as well? 

The second issue that I am seeing now is with the Lookup call. I am using the plugin api to lookup a function in the plugin as : 
```
 newRuntimeFunc, err := plug.Lookup("NewRuntimeVM")
                if err != nil {    
                        return nil, err
                }
```

But I am seeing a panic with this:
```
panic: interface conversion: plugin.Symbol is func(string) oci.RuntimeImpl, not func(string) oci.RuntimeImpl (types from different scopes)
```

Here is a similar issue someone else has come accross: https://github.com/golang/go/issues/30838
According to the comment on the issue:
```
In GOPATH mode, each vendor copy of a package is its own distinct package. That behavior will not be changing.

The solution is not to use vendor, or to use module mode with only a top-level vendor directory.
```

Which means it treats the RuntimeImpl from crio and its vendored copy in Kata as different types. 
Sounds, like the above issue could be solved by moving from `dep` that kata currently uses to go modules. I will need to try this out in Kata by moving to go modules though to see if this works. 

Another change I noticed would need to be made in the crio.conf file is to include two paths now, one for the plugin and one for the actual kata-shim binary itself. Any thoughts?

**Comment by amshinde** [comment] 2019-07-18 22:13
@mrunalp So, I tested out moving to go modules for kata in my branch. With this I was able to get the runtime binary building, but while building the plugin which has most of the code present today in runtime_vm.go today, I am seeing this error:
```
build command-line-arguments: cannot load k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2: cannot find module providing package k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2
```
I tried with using the same `replace` tags for the k8s.io packages that are present in the crio `go.mod` today as well as using the published repos for the packages, but still seeing the above error. 
Have you guys come accross this issue?

**Comment by mrunalp** [comment] 2019-07-18 22:17
Adding @saschagrunert and @vrothberg

**Comment by vrothberg** [comment] 2019-07-19 06:09
Thanks, @mrunalp!

The `RuntimeImpl` is an internal interface now but we can expose it again. My biggest concern is API stability and inter-operability (e.g., with containerd). Are there plans to support more than CRI-O with the `RuntimeImpl` and how mature is this API to guarantee stability? Once we expose it to be used (and loaded) by third parties we have to support it, so I want to be sure it's not a temporary solution.

**Comment by saschagrunert** [comment] 2019-07-19 06:47
> Have you guys come accross this issue?

Yeah, generally is should be possible to use the staging APIs mixed with the kubernetes local ones, but all of them should point to the same commit of Kubernetes (like we do with the rewrite in go.mod). Do you have any source code on GitHub where we could support you directly?

> Once we expose it to be used (and loaded) by third parties we have to support it, so I want to be sure it's not a temporary solution.

I agree and I would choose the opportunity to enhance the documentation (and publish them somewhere), because we would have to make some related types public, like `oci.Container`.

**Comment by saschagrunert** [comment] 2019-07-19 12:25
@amshinde If you want, then you can give https://github.com/cri-o/cri-o/pull/2633 a try. A working implementation would then look like this:

```go
package main

import (
	"context"
	"fmt"
	"io"
	"syscall"

	"github.com/cri-o/cri-o/pkg/oci"
	spec "github.com/opencontainers/runtime-spec/specs-go"
	"k8s.io/client-go/tools/remotecommand"
)

type myruntime struct {
}

func main() {
	rt := myruntime{}

	giveMe(rt)
}

func giveMe(rt oci.RuntimeImpl) {
	fmt.Printf("%v", rt)
}

func (m myruntime) CreateContainer(*oci.Container, string) error {
	return nil
}

func (m myruntime) StartContainer(*oci.Container) error {
	return nil
}

func (m myruntime) ExecContainer(
	*oci.Container, []string, io.Reader, io.WriteCloser, io.WriteCloser,
	bool, <-chan remotecommand.TerminalSize,
) error {
	return nil
}

func (m myruntime) ExecSyncContainer(
	*oci.Container, []string, int64,
) (*oci.ExecSyncResponse, error) {
	return nil, nil
}

func (m myruntime) UpdateContainer(
	*oci.Container, *spec.LinuxResources,
) error {
	return nil
}

func (m myruntime) StopContainer(
	context.Context, *oci.Container, int64,
) error {
	return nil
}

func (m myruntime) DeleteContainer(*oci.Container) error {
	return nil
}

func (m myruntime) UpdateContainerStatus(*oci.Container) error {
	return nil
}

func (m myruntime) PauseContainer(*oci.Container) error {
	return nil
}

func (m myruntime) UnpauseContainer(*oci.Container) error {
	return nil
}

func (m myruntime) ContainerStats(*oci.Container) (*oci.ContainerStats, error) {
	return nil, nil
}

func (m myruntime) SignalContainer(*oci.Container, syscall.Signal) error {
	return nil
}

func (m myruntime) AttachContainer(
	*oci.Container, io.Reader, io.WriteCloser, io.WriteCloser, bool,
	<-chan remotecommand.TerminalSize,
) error {
	return nil
}

func (m myruntime) PortForwardContainer(
	*oci.Container, int32, io.ReadWriter,
) error {
	return nil
}

func (m myruntime) ReopenContainerLog(*oci.Container) error {
	return nil
}

func (m myruntime) WaitContainerStateStopped(
	context.Context, *oci.Container,
) error {
	return nil
}
```

With a working `go.mod` file:
```
module github.com/saschagrunert/oci-test

go 1.12

require (
	github.com/cri-o/cri-o v0.0.0
	github.com/elazarl/goproxy/ext v0.0.0-20190711103511-473e67f1d7d2 // indirect
	github.com/opencontainers/runtime-spec v1.0.1
	k8s.io/client-go v0.0.0
)

replace (
	github.com/cri-o/cri-o => github.com/openSUSE/cri-o public-oci-interface
	github.com/godbus/dbus => github.com/godbus/dbus v0.0.0-20190623212516-8a1682060722
	github.com/opencontainers/runtime-spec => github.com/opencontainers/runtime-spec v0.1.2-0.20190408193819-a1b50f621a48
	k8s.io/api => k8s.io/kubernetes/staging/src/k8s.io/api v0.0.0-20190717003725-704790e04128
	k8s.io/apiextensions-apiserver => k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver v0.0.0-20190717003725-704790e04128
	k8s.io/apimachinery => k8s.io/kubernetes/staging/src/k8s.io/apimachinery v0.0.0-20190717003725-704790e04128
	k8s.io/apiserver => k8s.io/kubernetes/staging/src/k8s.io/apiserver v0.0.0-20190717003725-704790e04128
	k8s.io/cli-runtime => k8s.io/kubernetes/staging/src/k8s.io/cli-runtime v0.0.0-20190717003725-704790e04128
	k8s.io/client-go => k8s.io/kubernetes/staging/src/k8s.io/client-go v0.0.0-20190717003725-704790e04128
	k8s.io/cloud-provider => k8s.io/kubernetes/staging/src/k8s.io/cloud-provider v0.0.0-20190717003725-704790e04128
	k8s.io/cluster-bootstrap => k8s.io/kubernetes/staging/src/k8s.io/cluster-bootstrap v0.0.0-20190717003725-704790e04128
	k8s.io/code-generator => k8s.io/kubernetes/staging/src/k8s.io/code-generator v0.0.0-20190717003725-704790e04128
	k8s.io/component-base => k8s.io/kubernetes/staging/src/k8s.io/component-base v0.0.0-20190717003725-704790e04128
	k8s.io/cri-api => k8s.io/kubernetes/staging/src/k8s.io/cri-api v0.0.0-20190717003725-704790e04128
	k8s.io/csi-translation-lib => k8s.io/kubernetes/staging/src/k8s.io/csi-translation-lib v0.0.0-20190717003725-704790e04128
	k8s.io/kube-aggregator => k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator v0.0.0-20190717003725-704790e04128
	k8s.io/kube-controller-manager => k8s.io/kubernetes/staging/src/k8s.io/kube-controller-manager v0.0.0-20190717003725-704790e04128
	k8s.io/kube-proxy => k8s.io/kubernetes/staging/src/k8s.io/kube-proxy v0.0.0-20190717003725-704790e04128
	k8s.io/kube-scheduler => k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler v0.0.0-20190717003725-704790e04128
	k8s.io/kubectl => k8s.io/kubernetes/staging/src/k8s.io/kubectl v0.0.0-20190717003725-704790e04128
	k8s.io/kubelet => k8s.io/kubernetes/staging/src/k8s.io/kubelet v0.0.0-20190717003725-704790e04128
	k8s.io/kubernetes => k8s.io/kubernetes v1.16.0-alpha.1
	k8s.io/legacy-cloud-providers => k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers v0.0.0-20190717003725-704790e04128
	k8s.io/metrics => k8s.io/kubernetes/staging/src/k8s.io/metrics v0.0.0-20190717003725-704790e04128
	k8s.io/sample-apiserver => k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver v0.0.0-20190717003725-704790e04128
)
```

Are you still targeting to build a shared library or would it be enough if we depend on your go library? This way we could save efforts from my point of view.

**Comment by amshinde** [comment] 2019-07-19 18:29
@saschagrunert Thanks. I was using an older commit of crio 485227d before the oci package was made internal I suppose. Let me try with your branch and see if I run into similar issues.

> Are you still targeting to build a shared library or would it be enough if we depend on your go library? This way we could save efforts from my point of view.

Could you explain "depend on your library"?
I had started out with building a go plugin that implements just the shimv2 api client.

**Comment by saschagrunert** [comment] 2019-07-22 06:45
> Could you explain "depend on your library"?
> I had started out with building a go plugin that implements just the shimv2 api client.

Yes that's what I meant. :) I'm just wondering what the reasons behind "shared object vs simply go library" are?

**Comment by saschagrunert** [comment] 2019-07-22 10:48
@amshinde We internally decided to move the interface to libpod before continuing here (see the discussion on #2633). I will follow up on that topic and keep you posted.

@haircommander did you already start working on a migration like that? If not, should I go for it? Or do you think it is not the right time for such a migration?

**Comment by vrothberg** [comment] 2019-07-22 11:20
@saschagrunert, nothing's blocking a migration. There's the requirements doc (https://docs.google.com/document/d/1GKub_NvdGCo7veR8XXf5w3PaEpIwzU6TnTMKNDcErEA/edit?usp=sharing) to coordinate the efforts.

I suggest starting with the image API first. There is a lot of redundancy among CRI-O, Podman, and Buildah. I think that some things can be moved into c/image, and some be moved into libpod (e.g., CIDR handling). I opened https://github.com/containers/image/pull/658 last week which is an example of redundancy that could/should be moved into c/image.

**Comment by amshinde** [comment] 2019-07-23 22:33
@saschagrunert To continue with my testing, I had to make a few more api's in cri-o public that my plugin code was using. 
A hacked up crio version for this purpose: https://github.com/amshinde/cri-o/tree/more-public-oci-apis

And the corresponding wip kata plugin implementation: 
https://github.com/amshinde/kata-runtime/commits/shimv2-crio-plugin

With this, I had all the required api's exposed for my testing. With this in place, I ran into the  following issue:
```
POD_ID=$(sudo crictl runp test/testdata/sandbox_config.json)
FATA[0003] run pod sandbox failed: rpc error: code = Unknown desc = plugin.Open("/usr/local/bin/runtime_vm.so"): plugin was built with a different version of package github.com/cri-o/cri-o/pkg/oci (previous failure)
```
I found an issue in the golang repo describing the exact scenario, that is still open:
https://github.com/golang/go/issues/27751
The issue is seen when the plugin using go-modules includes an api from the app it is being called from, in this case cri-o. I am not sure if we move to libpod api, this issue would get solved entirely. 

Besides this, a fundamental limitation that I have come across while playing with plugins in go is:
1)  A go-plugin must be compiled with the same exact toolchain as the go program that it will be called from. This means go version needs to be the same as well as variables such as `GO111MODULE`
2) Any common dependencies between the plugin and the go-binary that it is called from need to be the same as well. (The dependencies cannot be vendored as well, as they are treated as different scope, as I documented in my previous comment)

This comment on of the golang issues confirms the above 2 obeservations:
https://github.com/golang/go/issues/28983#issuecomment-442640034

A possible yet not so ideal solution for 1) could be to maintain some kind of Dockerfile in cri-o repo, that the plugin in the kata repo could use. The container would make available the right go-environment for building the plugin.
But for 2), the plugin itself would need to keep track of any shared dependencies used by cri-o and update accordingly.  I dont think this is really feasible or sustainable in the long run.

Looking at the various issues I faced and that are currently open in the go repo, I am not sure if the plugin feature is quite production ready, they seem to work best if the plugin resides in the same repo as the code it is called from.  

cc @mrunalp

**Comment by haircommander** [comment] 2019-07-24 00:58
@saschagrunert Migrating the oci runtime interface to libpod is up on my list of things to do. I hope to start this week

**Comment by saschagrunert** [comment] 2019-07-24 06:45
@amshinde thank you for the detailed update and I see your concerns. Was maintaining the code on the kata side the only reason for approaching this way? Do you think it would be possible that you develop a go module for the OCI runtime and we use it (with a small boilerplate overhead) here as standard go dependency? This way we would avoid all the overhead with the shared objects and use the standard go way.

**Comment by amshinde** [comment] 2019-08-02 18:38
@saschagrunert That would require cri-o to vendor in kata code, which is not ideal.

@mrunalp I could not discuss further on the crio call the other day, the plugin limitations with go-modules are a blocker to go any further on this route. If you agree, let me know if we can close this one.

**Comment by fidencio** [comment] 2021-06-24 12:46
@sboeuf, @haircommander, is this still something to be considered? Or shall we close this one in case we're okay with the situation as it's Today?

**Comment by haircommander** [comment] 2021-06-24 13:28
yeah I'm not really sure the difficulties are worth the benefit. maybe if go ever gets better at plugins

**Closed by haircommander** 2021-06-24 13:28 UTC
Labels: area/vm
