### ISSUE TITLE
[1.16] crio refuse to delete pod if cni is not available 

### ISSUE THREAD

**Issue by Ehekatl** [cri-o/cri-o#4084] opened 2020-08-16 22:14 UTC
**Description**

There is no way to clean up the pods if cni is down
I was doing reset on a node, I removed all containers with crictl rm, but the pods are still there.
When I try run crictl stopp or crictl rmp -f, it always failed with timeout connect to cilium socket.

```
FAILED! => {"attempts": 5, "changed": true, "cmd": "crictl pods -q | xargs -r crictl -t 60s stopp", "delta": "0:00:30.071398", "end": "2020-08-16 21:12:29.501689", "msg": "non-zero return code", "rc": 123, "start": "2020-08-16 21:11:59.430291", "stderr": "time=\"2020-08-16T21:12:29Z\" level=fatal msg=\"stopping the pod sandbox \\\"1e4af534df58a2b0353cd13e220f36e32b99a85c7d0dc9ae0a826f4fa4cd91ac\\\" failed: rpc error: code = Unknown desc = failed to destroy network for pod sandbox k8s_ingress-kong-8675f794c-j98tc_kong_84a4a3dd-19f3-47d0-a8a7-fd3b1ae437da_0(1e4af534df58a2b0353cd13e220f36e32b99a85c7d0dc9ae0a826f4fa4cd91ac): unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory\\nIs the agent running?\"", "stderr_lines": ["time=\"2020-08-16T21:12:29Z\" level=fatal msg=\"stopping the pod sandbox \\\"1e4af534df58a2b0353cd13e220f36e32b99a85c7d0dc9ae0a826f4fa4cd91ac\\\" failed: rpc error: code = Unknown desc = failed to destroy network for pod sandbox k8s_ingress-kong-8675f794c-j98tc_kong_84a4a3dd-19f3-47d0-a8a7-fd3b1ae437da_0(1e4af534df58a2b0353cd13e220f36e32b99a85c7d0dc9ae0a826f4fa4cd91ac): unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory\\nIs the agent running?\""], "stdout": "", "stdout_lines": []}
```
I also tried clean cni config and restart crio first, then it give me error of Missing CNI default:

```
FAILED! => {"attempts": 5, "changed": true, "cmd": "crictl pods -q | xargs -r crictl -t 60s stopp", "delta": "0:00:00.013891", "end": "2020-08-16 21:56:42.667181", "msg": "non-zero return code", "rc": 123, "start": "2020-08-16 21:56:42.653290", "stderr": "time=\"2020-08-16T21:56:42Z\" level=fatal msg=\"stopping the pod sandbox \\\"c6183a1f83645940ba13c9191dc74200bd443076076531b486d95e12ebea31c8\\\" failed: rpc error: code = Unknown desc = failed to destroy network for pod sandbox k8s_coredns-5f65b4ff59-kbg86_kube-system_30e64d3a-b0c8-4d09-a100-9e3a13cb8e41_0(c6183a1f83645940ba13c9191dc74200bd443076076531b486d95e12ebea31c8): Missing CNI default network\"", "stderr_lines": ["time=\"2020-08-16T21:56:42Z\" level=fatal msg=\"stopping the pod sandbox \\\"c6183a1f83645940ba13c9191dc74200bd443076076531b486d95e12ebea31c8\\\" failed: rpc error: code = Unknown desc = failed to destroy network for pod sandbox k8s_coredns-5f65b4ff59-kbg86_kube-system_30e64d3a-b0c8-4d09-a100-9e3a13cb8e41_0(c6183a1f83645940ba13c9191dc74200bd443076076531b486d95e12ebea31c8): Missing CNI default network\""], "stdout": "", "stdout_lines": []}
```

the issue doesn't happen to crio 1.15

**Steps to reproduce the issue:**

1. setup cilium
2. rm cilium agent container
3. try delete crictl pod

**Describe the results you received:**

**Describe the results you expected:**

pod can always able to delete in someway

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.16.6
commit: "af8faf448858335f9645b896120167d08caf7156-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):

bare mental environment with cilium

**Comment by haircommander** [comment] 2020-08-17 16:13
The regressions is because we have begun to fail when we fail to tear down the network: https://github.com/cri-o/cri-o/pull/3164
This behaviour is intentional and I believe it is correct. It allows us to propagate errors from cni and have the kubelet appropriately retry when, for instance, a cni del request times out.

I am partially conflicted, but I do think this new behaviour is desired. If cri-o cannot reach the cni provider, then there are resources that will leak on pod removal. That's not really removing the pod. My recommendation would be to not remove the cni pod until the end (remove all pods, then cni) to make sure we don't get into this state. 

Is that a sufficient work around for you?

**Comment by Ehekatl** [comment] 2020-08-20 11:59
@haircommander 
for now we are creating a loopback cni config before clean all pods out.
Hacky but works, there should be a better way than this

**Comment by haircommander** [comment] 2020-09-30 15:08
I agree, but for that we'd need ordered shutdown support in crictl, which I believe is out of scope for CRI-O. CRI-O has to do what the CRI tells it to, which includes removing all pods when it's asked. I don't think there's a way for CRI-O to know a specific pod is providing the cni config. Since there's a work around, I am closing this.

**Closed by haircommander** 2020-09-30 15:08 UTC
