### ISSUE TITLE
Conmon doesn't forward error with runc

### ISSUE THREAD

**Issue by umohnani8** [cri-o/cri-o#1257] opened 2018-01-16 15:35 UTC
**Description**
The runc error is not forwarded out by conmon. Specifically https://github.com/kubernetes-incubator/cri-o/blob/master/conmon/conmon.c#L1302 says it needs to be fixed.
In some cases for podman, container creation fails but there is no error message making it hard to deduce what caused the failure.

**Comment by runcom** [comment] 2018-01-16 15:47
This https://github.com/kubernetes-incubator/cri-o/blob/master/conmon/conmon.c#L1306 should also be fixed to say "stdin" (not "stdout").

**Comment by runcom** [comment] 2018-01-16 15:50
BTW, that comment is pretty old and surely not relevant anymore https://github.com/kubernetes-incubator/cri-o/commit/4493b6f17631a23458436728adab4f961606be97#diff-caf7c5c19d8bb76309f55ccce30a55afL414 :confused: @mrunalp PTAL

**Comment by rhatdan** [comment] 2018-03-16 18:25
@umohnani8 @runcom Is someone working on this? Is this still an issue?  @baude @mheon aren't you guys seeing issues with this?

**Comment by mheon** [comment] 2018-03-16 18:27
Conmon is pretty good about throwing errors into syslog, but its double-fork makes them difficult to catch in `podman` - we still can't reliably get errors our of `runc`. I'd love to see improved conmon logging (a --debug flag, maybe?) and the option to output logs to file as well.

**Comment by rhatdan** [comment] 2018-03-16 18:50
@giuseppe PTAL

**Comment by umohnani8** [comment] 2019-03-15 18:25
@mheon @giuseppe is this still an issue? I can't recall if we fixed it.

**Comment by mheon** [comment] 2019-03-15 18:27
It's definitely still an issue. We lose a lot of errors when containers are started with a TTY - Conmon will try and retrieve the TTY from runc, and when the container fails to start we get an error about Conmon being unable to retrieve a TTY instead of the actual error that killed runc. The dreaded empty error messages from Conmon dying without signalling the cause of an error are also still present, but much less common.

**Comment by giuseppe** [comment] 2019-03-15 18:40
there were some improvements b431f36edc55106ef149fc85bb76b5455a128a40 but I've also noticed there are still cases where the errors from the OCI runtime are lost

**Comment by haircommander** [comment] 2020-04-29 17:41
closing this as it belongs in containers/conmon

**Closed by haircommander** 2020-04-29 17:41 UTC
