### ISSUE TITLE
arm64/armv7l | cri-o 17.xx | debian/ubuntu

### ISSUE THREAD

**Issue by chrstnwhlrt** [cri-o/cri-o#3294] opened 2020-02-17 10:21 UTC
Building / packaging cri-o v17.xx for arm64/armv7l failes for debian and ubuntu:

```
...
strip: Unable to recognise the format of the input file `debian/cri-o-1.17/usr/bin/crio-status'
dh_strip: strip --remove-section=.comment --remove-section=.note debian/cri-o-1.17/usr/bin/crio-status returned exit code 1
dh_strip: Aborting due to earlier error 
...
```

Same issue appears with the OBS build jobs: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-o-1.17

**Comment by mrunalp** [comment] 2020-02-28 05:12
@saschagrunert could you take a look?

**Comment by saschagrunert** [comment] 2020-02-28 09:55
@lsm5 how are these packages built? :thinking: 

I would assume that there is no further strip needed for the binary since it is already stripped via `-ldflags '-s -w …'`.

**Comment by rhafer** [comment] 2020-02-28 10:09
> ```strip: Unable to recognise the format of the input file `debian/cri-o-1.17/usr/bin/crio-status'```

It seems to me the issue is, that the `cri-o-1.17_1.17.0-3.tar.gz` (not sure where that is coming from and how it is generated) already contains `bin/crio-status` as a x86_64 binary.

```
cri-o-1.17/cri-o> file bin/crio-status
bin/crio-status: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=6262ee095456e2ac86261874d3a1baa4bb5bc0c9, for GNU/Linux 3.2.0, stripped
```

 `strip` on arm of course doesn't now what to do with that.

**Comment by lsm5** [comment] 2020-03-04 22:06
I built `1.17.0-6` on OBS testing repo, https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-1.17 . Disabled dh_strip along with a couple other dh_ commands. Packaging rules are at https://gitlab.com/rhcontainerbot/cri-o/-/blob/debian-testing-1.17/debian/rules . Lemme know how the build works for you.

**Comment by lsm5** [comment] 2020-03-04 22:07
If this looks good, I'll replicate for the stable repo as well.

**Comment by rhafer** [comment] 2020-03-05 08:17
@lsm5 The tarball in that  https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-1.17 still contains the x86_64 crio-status binary. Because of that the `make` command won't rebuild the crio-status for arm. (Which will now, that you removed the strip command, probably go unnoticed. But still result in a broken package for arm, and also result in something that you don't actually into for on x86_64).

**Comment by lsm5** [comment] 2020-03-07 12:18
@rhafer seems like there was leftover `bin/crio-status` which wasn't getting cleaned up before tarball generation. Should be fixed in `1.17.0-10` https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-1.17 . PTAL and sorry about the lag.

**Comment by dougsland** [comment] 2020-04-08 13:44
@lsm5 @rhafer @saschagrunert @haircommander  if https://github.com/cri-o/cri-o/pull/3488 solve this issue we might close this one ?

**Comment by haircommander** [comment] 2020-04-08 14:15
@chrstnwhlrt is your issue solved?

**Comment by haircommander** [comment] 2020-04-22 13:15
closing as it seems the issue is solved, please reopen if you disagree

**Closed by haircommander** 2020-04-22 13:15 UTC
