### ISSUE TITLE
OBS .repo files use http for downloading RPM gpgkeys which risks MITM attacks

### ISSUE THREAD

**Issue by matthias50** [cri-o/cri-o#3725] opened 2020-05-05 16:15 UTC
**Description**
The .repo files on OBS, for example https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.18.repo use http to download the gpg keys. This is opens up the possibility for hijacking the key download as there will be no TLS verification. 
```
gpgkey=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18/CentOS_7/repodata/repomd.xml.key
```
The key does seem to be served up https by OBS because I was able to manually download it using wget with https, so it seems odd that it is configured this way.

**Steps to reproduce the issue:**
Follow install instructions here: https://github.com/cri-o/cri-o
```
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION].repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION]/CentOS_7/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION].repo
sudo yum -y install cri-o
```
**Describe the results you received:**
gpg key gets downloaded via http

**Describe the results you expected:**
gpg key gets downloaded via https

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
N/A. Seems to be this way for all crio RPM repos on OBS
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by dougsland** [comment] 2020-05-05 20:44
Hi @matthias50, I believe this report should be created in OBS system. Please consider opening a ticket to openSuse Build Service, more info here: https://en.opensuse.org/openSUSE:Submitting_bug_reports

@saschagrunert

**Comment by adrianschroeter** [comment] 2020-05-11 15:03
future .repo files created by OBS will contain https:// URLs.

However keep in mind that trusting the SSL of the download server reduces the trust (and it can not work on mirrors). The safer way would be to download the key from OBS directly and verify against gpg key chain.

**Comment by haircommander** [comment] 2020-05-11 16:19
The problem is outside of cri-o's control, and there's a workaround to build trust (gpg keys). as such, I'm closing this

**Closed by haircommander** 2020-05-11 16:19 UTC
