### ISSUE TITLE
Not possible to install CRI-O on CentOS 8

### ISSUE THREAD

**Issue by GabyCT** [cri-o/cri-o#3130] opened 2020-01-20 19:25 UTC
I tried to do the installation for CRI-O on CentOS 8 (https://github.com/cri-o/cri-o/blob/master/tutorials/setup.md), however, I am getting a lot of problems mainly because of missing packages like `btrfs-progs-devel`, `libseccomp-devel`, `device-mappper-devel` and `pkgconfig`. Is there a way to install CRI-O on CentOS 8? thanks

**Comment by GabyCT** [comment] 2020-01-20 19:26
I tried to use the `rpms` from CentOS 7, however, I still got a lot failures mainly because of conflicting versions

**Comment by dougsland** [comment] 2020-01-20 19:34
@GabyCT Hi, which repos have you enabled on CentOS8? Have you enabled PowerTools ? I believe this repo should help. (Meanwhile, I am testing locally here too).

**Comment by GabyCT** [comment] 2020-01-20 19:39
@dougsland , here it is the info
```
$ yum repolist
CentOS-8 - AppsStream
CentOS-8 - Base
CentOS-8 - PowerTools
Docker CE Stable -x86_64
CentOS-8 - Extras
Extra Packages for Enterprise Linux 8 - x86_64
Extra Packages for Enterprise Linux Modular 8 - x86_64
```
yes, I have enabled the PowerTools repo but I still do not have those packages
```
[PowerTools]
name=CentOS-$releasever - PowerTools
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=PowerTools&infra=$infra
#baseurl=http://mirror.centos.org/$contentdir/$releasever/PowerTools/$basearch/os/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
```

**Comment by dougsland** [comment] 2020-01-20 21:10
@GabyCT just reproduced your report. btrfs-progs-devel package is not available yet for CentOS 8. The support for btrfs is not enabled by default, so you can skip this package when triggering dnf install (packages required for the build).

For the : 
   - pkgconfig, please use pkgconf-pkg-config. 
   - "device-mappper-devel", there is a typo in the package name with 3 "p" in your issue description.

Going to send a PR to improve our docs. 
Please let us know if the workaround works for you.

@lsm5 I am wondering if you have any info about btrfs-progs(-devel) packaging in EL8.

**Comment by GabyCT** [comment] 2020-01-20 21:40
@dougsland , I think that we need also `libseccomp-devel` (also not available) because if not is to possible to build it

**Comment by dougsland** [comment] 2020-01-20 22:05
@GabyCT looks like for me it's there:

# dnf info libseccomp-devel
Installed Packages
Name         : libseccomp-devel
Version      : 2.4.1
Release      : 1.el8
Arch         : x86_64
Size         : 426 k
Source       : libseccomp-2.4.1-1.el8.src.rpm
Repo         : @System
From repo    : AppStream
Summary      : Development files used to build applications with libseccomp support
URL          : https://github.com/seccomp/libseccomp
License      : LGPLv2
Description  : The libseccomp library provides an easy to use interface to the Linux Kernel's
             : syscall filtering mechanism, seccomp.  The libseccomp API allows an application
             : to specify which syscalls, and optionally which syscall arguments, the
             : application is allowed to execute, all of which are enforced by the Linux
             : Kernel.

Available Packages
Name         : libseccomp-devel
Version      : 2.4.1
Release      : 1.el8
Arch         : i686
Size         : 80 k
Source       : libseccomp-2.4.1-1.el8.src.rpm
Repo         : AppStream
Summary      : Development files used to build applications with libseccomp support
URL          : https://github.com/seccomp/libseccomp
License      : LGPLv2
Description  : The libseccomp library provides an easy to use interface to the Linux Kernel's
             : syscall filtering mechanism, seccomp.  The libseccomp API allows an application
             : to specify which syscalls, and optionally which syscall arguments, the
             : application is allowed to execute, all of which are enforced by the Linux
             : Kernel.

[root@localhost cri-o]# rpm -qa | grep libseccomp-devel
libseccomp-devel-2.4.1-1.el8.x86_64
[root@localhost cri-o]# cat /etc/redhat-release 
CentOS Linux release 8.0.1905 (Core)

**Comment by lsm5** [comment] 2020-01-21 14:21
> @lsm5 I am wondering if you have any info about btrfs-progs(-devel) packaging in EL8.

hi @dougsland , afaik, you can use buildtag `exclude_graphdriver_btrfs` to skip any btrfs deps.

**Comment by lsm5** [comment] 2020-01-21 14:21
Also, I plan to provide centos8 binaries via the kubic project repos on OBS.

**Comment by GabyCT** [comment] 2020-01-21 15:48
@dougsland , that is weird , I do not have it (I am using an Azure CentOS image)
```
$ rpm -qa | grep libseccomp-devel
$ yum search libseccomp-devel
Last metadata expiration check: 0:01:25 ago on mar 21 ene 2020 15:46:08 UTC.
No matches found.
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by dougsland** [comment] 2020-01-21 22:02
@GabyCT I can see the package in the CentOS mirror too: 
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libseccomp-devel-2.4.1-1.el8.x86_64.rpm

**Comment by dougsland** [comment] 2020-01-22 15:14
@GabyCT Have you solved the package dep? Can we close this issue? Maybe open a specific for btrfs-progs-devel package not available yet for CentOS 8.

**Comment by GabyCT** [comment] 2020-01-22 20:04
@dougsland , I still have issues with the packages in CentOS 8, for exmaple when I am trying to install `device-mapper-devel`, I got the following
```
Error:
 Problem 1: cannot install the best candidate for the job
  - nothing provides device-mapper = 8:1.02.163-5.el8.0.1 needed by device-mapper-devel-8:1.02.163-5.el8.0.1.x86_64
```
Which is weird because I tried to install `device-mapper` before and I got the same error.
Another issue is `glibc-static`
```
Problem 2: cannot install the best candidate for the job
  - nothing provides glibc-devel = 2.28-72.el8 needed by glibc-static-2.28-72.el8.x86_64
```

**Comment by dougsland** [comment] 2020-01-22 21:16
Hi @GabyCT ,

Could you please share:

# dnf repolist -v

and

Attach a tarball from /var/cache/dnf so we can try to reproduce your issue.

**Comment by GabyCT** [comment] 2020-01-22 21:32
@dougsland , here it is
```
$ dnf repolist -v
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.0.9
cachedir: /var/cache/dnf
repo: using cache for: BaseOS
not found other for: CentOS-8 - Base
not found modules for: CentOS-8 - Base
not found deltainfo for: CentOS-8 - Base
not found updateinfo for: CentOS-8 - Base
BaseOS: using metadata from mar 26 nov 2019 18:57:28 UTC.
repo: using cache for: AppStream
not found other for: CentOS-8 - AppStream
not found modules for: CentOS-8 - AppStream
not found deltainfo for: CentOS-8 - AppStream
not found updateinfo for: CentOS-8 - AppStream
AppStream: using metadata from mar 26 nov 2019 18:54:26 UTC.
repo: using cache for: extras
not found other for: CentOS-8 - Extras
not found modules for: CentOS-8 - Extras
not found deltainfo for: CentOS-8 - Extras
not found updateinfo for: CentOS-8 - Extras
extras: using metadata from vie 10 ene 2020 18:31:29 UTC.
repo: using cache for: PowerTools
not found other for: CentOS-8 - PowerTools
not found deltainfo for: CentOS-8 - PowerTools
not found updateinfo for: CentOS-8 - PowerTools
PowerTools: using metadata from mié 22 ene 2020 18:27:56 UTC.
repo: using cache for: docker-ce-stable
not found other for: Docker CE Stable - x86_64
not found modules for: Docker CE Stable - x86_64
not found deltainfo for: Docker CE Stable - x86_64
docker-ce-stable: using metadata from jue 14 nov 2019 17:47:37 UTC.
repo: using cache for: epel-modular
not found other for: Extra Packages for Enterprise Linux Modular 8 - x86_64
not found deltainfo for: Extra Packages for Enterprise Linux Modular 8 - x86_64
epel-modular: using metadata from lun 20 ene 2020 03:45:58 UTC.
repo: using cache for: epel
not found other for: Extra Packages for Enterprise Linux 8 - x86_64
not found modules for: Extra Packages for Enterprise Linux 8 - x86_64
epel: using metadata from mié 22 ene 2020 02:05:13 UTC.
Last metadata expiration check: 0:00:40 ago on mié 22 ene 2020 21:31:06 UTC.
Completion plugin: Generating completion cache...

Repo-id      : AppStream
Repo-name    : CentOS-8 - AppStream
Repo-revision: 1574794430
Repo-updated : mar 26 nov 2019 18:54:26 UTC
Repo-pkgs    : 5 532
Repo-size    : 8.7 G
Repo-baseurl : http://olcentgbl.trafficmanager.net/centos/8/AppStream/x86_64/os/
Repo-expire  : 172 800 second(s) (last: mié 22 ene 2020 21:30:57 UTC)
Repo-filename: /etc/yum.repos.d/CentOS-AppStream.repo

Repo-id      : BaseOS
Repo-name    : CentOS-8 - Base
Repo-revision: 1574794604
Repo-updated : mar 26 nov 2019 18:57:28 UTC
Repo-pkgs    : 2 847
Repo-size    : 3.8 G
Repo-baseurl : http://olcentgbl.trafficmanager.net/centos/8/BaseOS/x86_64/os/
Repo-expire  : 172 800 second(s) (last: mié 22 ene 2020 21:30:52 UTC)
Repo-filename: /etc/yum.repos.d/CentOS-Base.repo

Repo-id      : PowerTools
Repo-name    : CentOS-8 - PowerTools
Repo-revision: 1579717676
Repo-updated : mié 22 ene 2020 18:27:56 UTC
Repo-pkgs    : 1 499
Repo-size    : 1.0 G
Repo-mirrors : http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=PowerTools&infra=stock
Repo-baseurl : http://repo1.sea.innoscale.net/centos/8.1.1911/PowerTools/x86_64/os/ (9 more)
Repo-expire  : 172 800 second(s) (last: mié 22 ene 2020 21:31:02 UTC)
Repo-filename: /etc/yum.repos.d/CentOS-PowerTools.repo

Repo-id      : docker-ce-stable
Repo-name    : Docker CE Stable - x86_64
Repo-revision: 1573753657
Repo-updated : jue 14 nov 2019 17:47:37 UTC
Repo-pkgs    : 63
Repo-size    : 1.4 G
Repo-baseurl : https://download.docker.com/linux/centos/7/x86_64/stable
Repo-expire  : 172 800 second(s) (last: mié 22 ene 2020 21:31:04 UTC)
Repo-filename: /etc/yum.repos.d/docker-ce.repo

Repo-id      : epel
Repo-name    : Extra Packages for Enterprise Linux 8 - x86_64
Repo-revision: 1579658673
Repo-updated : mié 22 ene 2020 02:05:13 UTC
Repo-pkgs    : 4 450
Repo-size    : 5.1 G
Repo-metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=x86_64&infra=stock&content=centos
  Updated    : mié 22 ene 2020 21:31:06 UTC
Repo-baseurl : http://pubmirror2.math.uh.edu/fedora-buffet/epel/8/Everything/x86_64/ (114 more)
Repo-expire  : 172 800 second(s) (last: mié 22 ene 2020 21:31:06 UTC)
Repo-filename: /etc/yum.repos.d/epel.repo

Repo-id      : epel-modular
Repo-name    : Extra Packages for Enterprise Linux Modular 8 - x86_64
Repo-revision: 1579491937
Repo-updated : lun 20 ene 2020 03:45:58 UTC
Repo-pkgs    : 0
Repo-size    : 0
Repo-metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-modular-8&arch=x86_64&infra=stock&content=centos
  Updated    : mié 22 ene 2020 21:31:05 UTC
Repo-baseurl : http://mirror.cs.pitt.edu/epel/8/Modular/x86_64/ (119 more)
Repo-expire  : 172 800 second(s) (last: mié 22 ene 2020 21:31:05 UTC)
Repo-filename: /etc/yum.repos.d/epel-modular.repo

Repo-id      : extras
Repo-name    : CentOS-8 - Extras
Repo-revision: 1578681089
Repo-updated : vie 10 ene 2020 18:31:29 UTC
Repo-pkgs    : 3
Repo-size    : 46 k
Repo-mirrors : http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=extras&infra=stock
Repo-baseurl : http://repo1.sea.innoscale.net/centos/8.1.1911/extras/x86_64/os/ (9 more)
Repo-expire  : 172 800 second(s) (last: mié 22 ene 2020 21:31:00 UTC)
Repo-filename: /etc/yum.repos.d/CentOS-Extras.repo
Total packages: 14 394
```
Let me create the tarball too, thanks for everything

**Comment by afbjorklund** [comment] 2020-01-22 21:57
> Also, I plan to provide centos8 binaries via the kubic project repos on OBS.

Will these replace the current PPA/CBS packages, for all of the distributions ?

Currently Kubernetes users seem to be confused, about _how_ to install cri-o/crictl.
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o

It would be nice if there was some good upstream documentation, to point users to.

**Comment by lsm5** [comment] 2020-01-23 04:00
> > Also, I plan to provide centos8 binaries via the kubic project repos on OBS.
> 
> Will these replace the current PPA/CBS packages, for all of the distributions ?

nothing on cbs or ppa for centos8. There's already cri-o-1.16 on stable and testing obs repos (docs updated for release-1.16), and cri-o-1.17 on testing repo (needs doc update). crictl is yet to be done. Unless there's some convenient official setup info for CentOS 8/Stream, I'll be putting centos8 stuff on OBS. 

> 
> Currently Kubernetes users seem to be confused, about _how_ to install cri-o/crictl.
> https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o

I'll update the doc there as well.

> 
> It would be nice if there was some good upstream documentation, to point users to.

see the [install doc](https://github.com/cri-o/cri-o/blob/release-1.16/README.md#installing-crio) on release-1.16 branch.

**Comment by afbjorklund** [comment] 2020-01-23 18:50
> > It would be nice if there was some good upstream documentation, to point users to.
> 
> see the [install doc](https://github.com/cri-o/cri-o/blob/release-1.16/README.md#installing-crio) on release-1.16 branch.

Thanks, seem like those kubic repos were not on `master` (https://github.com/cri-o/cri-o)

**Comment by lsm5** [comment] 2020-01-24 15:12
> > > It would be nice if there was some good upstream documentation, to point users to.
> > 
> > 
> > see the [install doc](https://github.com/cri-o/cri-o/blob/release-1.16/README.md#installing-crio) on release-1.16 branch.
> 
> Thanks, seem like those kubic repos were not on `master` (https://github.com/cri-o/cri-o)

yup, haven't PR'd to master yet, I'll do that.

**Comment by boekhold** [comment] 2020-02-01 12:57
> see the [install doc](https://github.com/cri-o/cri-o/blob/release-1.16/README.md#installing-crio) on release-1.16 branch.

If those instructions ever were correct, they are not anymore. I just did a fresh install of CentOS 8 and OpenSUSE Leap 15.1, and then followed the instructions from this page to the letter. 

**OpenSuse**
```
> sudo zypper install cri-o
Loading repository data...
Reading installed packages...
'cri-o' not found in packages nams. Trying capabilities.
No provider of 'cri-o' found.
Resolving package dependencies...

Nothing to do.
>
```

**CentOS8**
```
[...]$ sudo yum install crio
Last metadata expiration check: 0:00:55 ago on Sat 01 Feb 2020 07:53:47 AM EST
No match for argument: crio
Error: Unable to find a match: crio
[...]$
```

**Comment by boekhold** [comment] 2020-02-02 14:48
> > see the [install doc](https://github.com/cri-o/cri-o/blob/release-1.16/README.md#installing-crio) on release-1.16 branch.
> 
> If those instructions ever were correct, they are not anymore. I just did a fresh install of CentOS 8 and OpenSUSE Leap 15.1, and then followed the instructions from this page to the letter.

Ahhh, apologies.I just noticed that your link to "install.md" is actually linking to "README.md", so I was following the wrong instructions. Just read the "setup.md" as per your PR.

Is it therefore right to conclude that (at the moment) you need to build CRI-O from source for CentOS 8? No rpms available anywhere?

**Comment by boekhold** [comment] 2020-02-02 15:46
I've not built CRI-O itself yet, but to get all the listed dependencies installed, I needed to run:

```
sudo dnf config-manager --set-enabled PowerTools
```
(case-sensitive)

This isn''t mentioned in setup.md... I also enabled EPEL (`sudo dnf install epel-release`), which I'm not sure is required.

**Comment by lsm5** [comment] 2020-02-02 22:27
> > > see the [install doc](https://github.com/cri-o/cri-o/blob/release-1.16/README.md#installing-crio) on release-1.16 branch.
> > 
> > 
> > If those instructions ever were correct, they are not anymore. I just did a fresh install of CentOS 8 and OpenSUSE Leap 15.1, and then followed the instructions from this page to the letter.
> 
> Ahhh, apologies.I just noticed that your link to "install doc" is actually linking to "README.md", not "setup.md", which is what your PR is improving, so I was following the wrong instructions.
> 
> Is it therefore right to conclude that (at the moment) you need to build CRI-O from source for CentOS 8? No rpms available anywhere?

Haven't setup cri-o on centos8 yet but I'm working on putting it and other tools on OBS. There install doc updates I mentioned earlier were meant for ubuntu and debian. Sorry about the confusion.

If you're feeling adventurous, maybe you can try out the fedora rpms on centos, but no guarantees.

**Comment by boekhold** [comment] 2020-02-03 06:07
Pfew, took some effort, but I have k8s (almost) running with cri-o on CentOS 8. Built cri-o & conmon from source, installed kubeadm/kubectl/kubelet from the following repo:

```
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

Edited `/etc/sysconfig/kubelet` to add:

```
KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint="unix:///var/run/crio/crio.sock"
```
(note, most instructions on the net refer to `/etc/default/kubelet`, which is wrong)

Ran `modprobe br_netfilter` and `modprobe overlay` (also added entries to `/etc/modules-load.d`).

Make sure services are running correctly:
```
sudo systemctl daemon-reload
sudo systemctl restart cri-o
sudo systemctl restart kubelet
```

Then ran `sudo kubeadm init`, which completed successfully. The only remaining issue seems to be that the CoreDNS pods go into a CrashLoopBackOff. I applied thr trick to allow priviledge escalation but it doesn't help. Also, `kubelet` is running with `--resolv-conf=/run/systemd/resolve/resolv.conf`, which is pointing to the correct actual DNS server.

```
boekhold@centos8 ~]$ kubectl get pods --all-namespaces
NAMESPACE     NAME                              READY   STATUS             RESTARTS   AGE
kube-system   coredns-5d95487b75-g9bxx          0/1     CrashLoopBackOff   4          2m50s
kube-system   coredns-5d95487b75-rbkqk          0/1     CrashLoopBackOff   4          2m50s
kube-system   coredns-6955765f44-zcqdx          0/1     CrashLoopBackOff   8          17m
kube-system   etcd-centos8                      1/1     Running            0          16m
kube-system   kube-apiserver-centos8            1/1     Running            0          16m
kube-system   kube-controller-manager-centos8   1/1     Running            0          16m
kube-system   kube-proxy-qmxw6                  1/1     Running            0          17m
kube-system   kube-scheduler-centos8            1/1     Running            0          16m
```

I sincerely hope that your OBS packages will make this easier in the future!

**Comment by han-so1omon** [comment] 2020-03-07 07:40
To add to this, the command `make test-image-nix` produces a build error for me on Centos8

**Comment by dougsland** [comment] 2020-03-15 15:52
> To add to this, the command `make test-image-nix` produces a build error while building the libuv dependency for me on Centos8

I remember to see a patch get merged referencing such issue. Could you please re-try? I think it deserve a unique issue opened for this report to avoid mix a bunch of errors in a single report (CentOS8).

**Comment by dougsland** [comment] 2020-03-28 14:55
@GabyCT if you don't have additional questions, we can close this one. Fell free to re-open anytime. @mrunalp @haircommander

**Closed** 2020-03-29 11:03 UTC
