### ISSUE TITLE
kata tests are broken

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6481] opened 2023-01-03 18:52 UTC
### Which jobs are failing?

kata-jenkins

### Which tests are failing?

looks like cri-o has been failing to setup: http://jenkins.katacontainers.io/job/kata-containers-2-crio-PR/4525/consoleFull

### Since when has it been failing?

Pre-holiday, I overrode it to release 1.26.0 a number of times

**Comment by haircommander** [comment] 2023-01-03 18:52
If I had to guess, i'd guess it's due to https://github.com/cri-o/cri-o/pull/6289

cc @fidencio @littlejawa

**Comment by amarlearning** [comment] 2023-01-04 07:02
I would like to work on this issue.

**Comment by littlejawa** [comment] 2023-01-04 09:07
> If I had to guess, i'd guess it's due to #6289
> 

Right, that's probably the root cause.

@amarlearning - I'm not sure how familiar you are with kata containers, so let me give you some background. Sorry if that's redundant :-/
The CI job for kata on cri-o doesn't use the config from the cri-o repository. It uses scripts from the kata repository, shared with all other kata CI jobs.
For instance, this is how we install the cni plugins: https://github.com/kata-containers/tests/blob/main/.ci/install_cni_plugins.sh 

As for the config file, I think we reuse the default config from containerd.
Maybe *that* is the issue actually - it used to be similar, but your PR is moving away from that config, and now we can't rely on it anymore? 
That's just a guess from my side, as a first glance.

I will do some tests on my side to understand it better. If you do anything on the kata repository, please ping me so that I can get a look :)

**Comment by amarlearning** [comment] 2023-01-04 15:37
@littlejawa yes, you are right, I have zero experience with Kata containers. With community help, I believe I can do it.

Btw, I was going through the Jenkins build URL that @haircommander shared in the issue and found that one of the reasons why the build is failing is because 

```
00:14:51 cp: cannot stat '/tmp/jenkins/workspace/kata-containers-2-crio-PR/go/src/github.com/cri-o/cri-o/contrib/cni/10-crio-bridge.conf': No such file or directory
00:14:51 INFO: Environment initialization failed. Clean up and try again.
```

It's the same issue that I fixed in PR #6476, I believe once this commit gets merged to release 1.26 of CRI-O, the Jenkins kata container build will be fixed.

I haven't checked the full logs, will update this comment if I find something else.

**Comment by littlejawa** [comment] 2023-01-05 08:58
Hi @amarlearning - right, this is probably the issue.
I made a pull request to fix that, let's see how the CI behaves on the kata side.
(see https://github.com/kata-containers/tests/pull/5363)

**Comment by amarlearning** [comment] 2023-01-05 09:18
@littlejawa Thanks 👍🏻

**Comment by littlejawa** [comment] 2023-01-13 08:25
Looks similar to [#805](https://github.com/containernetworking/plugins/issues/805)

**Comment by littlejawa** [comment] 2023-01-17 13:49
If I use the ipv4 config file, still using CNI 0.3.1, the test passes, and I can go further.

This lead to another error, with a specific integration test: "ctr pod lifecycle with evented pleg enabled", which was introduced by #6404
Working on it (see: https://github.com/cri-o/cri-o/pull/6531).

So at this point, we need two things to get kata-jenkins job back to normal:
- use the fix from https://github.com/containernetworking/plugins/issues/805 (at the moment, it is merged, but I don't think we're using it yet?)
- have #6531 approved and merged (some discussion is required to confirm I have the right fix)

**Comment by littlejawa** [comment] 2023-01-20 08:46
#6541 was merged, using the latest CNI plugins with the fix in it.
Now the kata job still has the "mac address error" above, because this job is still using v1.1.1
I'm trying to fix that here : https://github.com/kata-containers/kata-containers/pull/6111

**Comment by littlejawa** [comment] 2023-01-26 11:00
All CNI-related issues seems to be gone now.
What remains is the failure on "ctr pod lifecycle with evented pleg enabled".
This is still being discussed on #6531

**Closed** 2023-02-08 08:20 UTC
Labels: kind/failing-test
