### ISSUE TITLE
runtime_type="vm" makes cri-o to send a panic: runtime error.

### ISSUE THREAD

**Issue by chavafg** [cri-o/cri-o#2672] opened 2019-07-25 15:53 UTC
**Description**

Tried to run kata-containers shimv-v2 with cri-o using `runtime_type= "vm"`.
I could run some k8s pods using this configuration, but after restarting my k8s cluster and cri-o service, cri-o cannot start successfully and sends panic errors described below. 

**Steps to reproduce the issue:**
1. add the next configuration to the `crio.runtime.runtimes` table:
```
[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_type = "vm"
```
2. start cri-o service

3. run some pods using k8s and kata.

4. restart the cri-o service.

5. after restarting the cri-o service, it will not start successfully

**Describe the results you received:**
cri-o crashes with `panic: runtime error: invalid memory address or nil pointer dereference`

```
Jul 25 14:11:07 crioshimv2 systemd[1]: Started CRI-O daemon.
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.110386316Z" level=debug msg="found valid runtime \"runc\" for runtime_path \"/usr/local/bin/crio-runc\"" file="config/config.go:701"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.110704217Z" level=debug msg="found valid runtime \"kata\" for runtime_path \"/usr/local/bin/kata-runtime\"" file="config/config.go:701"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.110844418Z" level=debug msg="using conmon from $PATH" file="config/config.go:717"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.110895918Z" level=info msg="using conmon executable \"/usr/local/bin/conmon\"" file="config/config.go:721"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.112101424Z" level=debug msg="cached value indicated that overlay is supported" file="overlay/overlay.go:175"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.112210924Z" level=debug msg="cached value indicated that metacopy is not being used" file="overlay/overlay.go:209"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.113232329Z" level=debug msg="cached value indicated that native-diff is not being used" file="overlay/overlay.go:450"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.113274929Z" level=warning msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVE
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.113746731Z" level=debug msg="backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false" file="overlay/overlay.go:27
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.113816232Z" level=info msg="[graphdriver] using prior storage driver: overlay" file="drivers/driver.go:270"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.120265161Z" level=info msg="no seccomp profile specified, using the internal default" file="server/server.go:371"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.120401062Z" level=info msg="installing default apparmor profile: crio-default-1.15.1-dev" file="server/server.go:377"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.149914198Z" level=debug msg="Golang's threads limit set to 115110" file="server/server.go:270"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.153027713Z" level=debug msg="oci.newRuntimeVM() start" file="oci/runtime_vm.go:60"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.153087313Z" level=debug msg="oci.newRuntimeVM() end" file="oci/runtime_vm.go:75"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.153128213Z" level=debug msg="runtimeVM.UpdateContainerStatus() start" file="oci/runtime_vm.go:549"
Jul 25 14:11:07 crioshimv2 crio[118096]: time="2019-07-25 14:11:07.153208814Z" level=debug msg="runtimeVM.UpdateContainerStatus() end" file="runtime/panic.go:522"
Jul 25 14:11:07 crioshimv2 crio[118096]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 25 14:11:07 crioshimv2 crio[118096]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x1774e10]
Jul 25 14:11:07 crioshimv2 crio[118096]: goroutine 1 [running]:
Jul 25 14:11:07 crioshimv2 crio[118096]: github.com/cri-o/cri-o/internal/oci.(*runtimeVM).UpdateContainerStatus(0xc00032ea80, 0xc0004686e0, 0x0, 0x0)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/internal/oci/runtime_vm.go:556 +0x190
Jul 25 14:11:07 crioshimv2 crio[118096]: github.com/cri-o/cri-o/internal/oci.(*Runtime).UpdateContainerStatus(0xc00041bfb0, 0xc0004686e0, 0x0, 0xc0001af970)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/internal/oci/oci.go:301 +0x7d
Jul 25 14:11:07 crioshimv2 crio[118096]: github.com/cri-o/cri-o/internal/lib.(*ContainerServer).ContainerStateFromDisk(0xc0000b1a40, 0xc0004686e0, 0x1d91f01, 0x1b)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/internal/lib/container_server.go:547 +0x61
Jul 25 14:11:07 crioshimv2 crio[118096]: github.com/cri-o/cri-o/internal/lib.(*ContainerServer).LoadSandbox(0xc0000b1a40, 0xc000286480, 0x40, 0x0, 0x0)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/internal/lib/container_server.go:409 +0x1665
Jul 25 14:11:07 crioshimv2 crio[118096]: github.com/cri-o/cri-o/server.(*Server).restore(0xc00047c900)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/server/server.go:171 +0x70f
Jul 25 14:11:07 crioshimv2 crio[118096]: github.com/cri-o/cri-o/server.New(0x20b35a0, 0xc00015a380, 0xc0001586e0, 0x1d81afb, 0x13, 0x20829a0, 0xc0001e8a80, 0x20a4420, 0xc000378de0, 0x0)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/server/server.go:389 +0xc89
Jul 25 14:11:07 crioshimv2 crio[118096]: main.main.func2(0xc000158840, 0xc000158840, 0xc0003c8af7)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/cmd/crio/main.go:606 +0x5e3
Jul 25 14:11:07 crioshimv2 crio[118096]: github.com/cri-o/cri-o/vendor/github.com/urfave/cli.HandleAction(0x1a9cd00, 0xc00012be20, 0xc000158840, 0xc000178060, 0x0)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/vendor/github.com/urfave/cli/app.go:490 +0xc8
Jul 25 14:11:07 crioshimv2 crio[118096]: github.com/cri-o/cri-o/vendor/github.com/urfave/cli.(*App).Run(0xc000503520, 0xc00003c090, 0x3, 0x3, 0x0, 0x0)
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/vendor/github.com/urfave/cli/app.go:264 +0x590
Jul 25 14:11:07 crioshimv2 crio[118096]: main.main()
Jul 25 14:11:07 crioshimv2 crio[118096]:         /home/fuentess/go/src/github.com/cri-o/cri-o/cmd/crio/main.go:719 +0x371c
Jul 25 14:11:07 crioshimv2 systemd[1]: crio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 25 14:11:07 crioshimv2 systemd[1]: crio.service: Failed with result 'exit-code'.
```

**Describe the results you expected:**
Expected to have cri-o service running without panic errors.

**Additional information you deem important (e.g. issue happens only occasionally):**
This only happens when using `runtime_type = "vm"`.
When using with`runtime_type = "oci"`, cri-o starts successfully. But this runtime type cannot be used for kata shim v2.

**Output of `crio --version`:**

```
crio version 1.15.1-dev
commit: "e56cddc00c57061307267dfa4b25ea8b6a33e327"
```
This also happens with cri-o v1.14.6 and with v1.15.0

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure VM with ubuntu 18.04

**Comment by chavafg** [comment] 2019-07-25 15:53
related https://github.com/kata-containers/tests/issues/1624

/cc @amshinde @sboeuf

**Comment by haircommander** [comment] 2019-08-15 18:27
@chavafg are you still seeing this?

**Comment by amshinde** [comment] 2019-08-16 23:32
@haircommander I'll take a look at this.
@chavafg Can you let me know the exact version of cri-o that you were using, along with the steps you followed to restart the cluster ?

**Comment by chavafg** [comment] 2019-08-19 14:06
hi @amshinde, version was:
```
crio version 1.15.1-dev
commit: "e56cddc00c57061307267dfa4b25ea8b6a33e327"
```

I've just configured cri-o as stated above and ran a simple workload using k8s (but using `crictl` should also get you to the issue).  
Then, try to restart cri-o service: `systemctl restart crio` and you should see the panic.

**Comment by amshinde** [comment] 2019-08-19 23:42
Took at initial look at this. The crash is seen at line:
https://github.com/cri-o/cri-o/blob/master/internal/oci/runtime_vm.go#L556

when UpdateContainerStatus is called while restoring containers from saved state.
In shimv2 case, the `r.task` is still nil, and hence the crash.
This field is only assigned in `startRuntimeDaemon`, when the shim binary is actually started.

cc @sboeuf

**Comment by amshinde** [comment] 2019-08-21 21:47
I am seeing this behaviour with crio in general, when I restart crio I see that all the containers are stopped as well. I see this in case of runc as well as kata shimv1 containers.
I would expect the containers to be around along with the conmon processes when crio is started.
cc @ganeshmaharaj who had seen some issues with crio restart earlier.
@mrunalp Can someone take a look at this? 

On a side note, the crash mentioned in this issue is also see when when  Kata shimv2 container is started and stopped prior to restarting crio, as an UpdateContainer for the container is called when the shimv2 is no longer around.

**Comment by sboeuf** [comment] 2020-04-14 07:18
@amshinde @chavafg the `restore()` code path for `VmRuntime` is not implemented correctly I think. There are some subtle save and restore actions which needs to happen if we want to make sure the crio daemon can be restarted while containers are running.
One that comes to mind is the ability to reconnect to each container `pty` to communicate with them after crio daemon is up and running again. There are some specific information which needs to be stored for the `VmRuntime`, which are essential to perform a proper restore.

**Comment by haircommander** [comment] 2020-04-29 19:31
due to https://github.com/cri-o/cri-o/issues/2672#issuecomment-613269157, It seems this is more a duplicate of https://github.com/cri-o/cri-o/issues/2112. As such, I'm closing this. please reopen if you disgaree

**Closed by haircommander** 2020-04-29 19:31 UTC
