### ISSUE TITLE
Joining worker node not starting flannel or kube-proxy / CRI-O error "open /dev/stderr: no such device or address"

### ISSUE THREAD

**Issue by joost14** [cri-o/cri-o#2368] opened 2019-05-14 08:44 UTC
**Description**
I have got a working master node and worker node and wanting to join a second worker node to my cluster. Both master and worker have been configured with CRI-O 1.13.1-dev.  But after joining the worker node to the cluster it does not start the networking pods and the service status gave some errors after joining. 
I followed the kubeadm guide: 
https://github.com/cri-o/cri-o/blob/master/tutorials/kubeadm.md 

**Steps to reproduce the issue:**
Join new worker node to existing (CRI-O) kubeadm cluster 

**Describe the results you received:**
Before joining existing cluster crio was started correctly: 
```
● crio.service - Open Container Initiative Daemon
   Loaded: loaded (/lib/systemd/system/crio.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-05-07 11:43:01 CEST; 6 days ago
     Docs: https://github.com/kubernetes-sigs/cri-o
 Main PID: 26175 (crio)
    Tasks: 15
   CGroup: /system.slice/crio.service
           └─26175 /usr/bin/crio

mei 07 11:43:01 k8smaster systemd[1]: Starting Open Container Initiative Daemon...
mei 07 11:43:01 k8smaster systemd[1]: Started Open Container Initiative Daemon.
 
```

After joining some errors occurred: 
```
crio.service - Open Container Initiative Daemon
   Loaded: loaded (/lib/systemd/system/crio.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-05-14 10:26:28 CEST; 3min 0s ago
     Docs: https://github.com/kubernetes-sigs/cri-o
 Main PID: 704 (crio)
    Tasks: 16
   CGroup: /system.slice/crio.service
           └─704 /usr/bin/crio

mei 14 10:29:25 k8sworker02 crio[704]:    --log-format value  set the format used by logs ('text' (default), or 'j
mei 14 10:29:25 k8sworker02 crio[704]:    --root value        root directory for storage of container state (this 
mei 14 10:29:25 k8sworker02 crio[704]:    --criu value        path to the criu binary used for checkpoint and rest
mei 14 10:29:25 k8sworker02 crio[704]:    --systemd-cgroup    enable systemd cgroup support, expects cgroupsPath t
mei 14 10:29:25 k8sworker02 crio[704]:    --rootless value    ignore cgroup permission errors ('true', 'false', or
mei 14 10:29:25 k8sworker02 crio[704]:    --help, -h          show help
mei 14 10:29:25 k8sworker02 crio[704]:    --version, -v       print the version
mei 14 10:29:25 k8sworker02 crio[704]:    
mei 14 10:29:25 k8sworker02 crio[704]: time="2019-05-14T10:29:25+02:00" level=error msg="open /dev/stderr: no such
mei 14 10:29:25 k8sworker02 crio[704]: open /dev/stderr: no such device or address
```
And some pods are not starting: 
```
kube-system   kube-flannel-ds-amd64-6thzn                      0/1     Init:0/1            0          58m
kube-system   kube-proxy-x8h48                                 0/1     ContainerCreating   0          59m

```

Output of kubectl describe pod kube-flannel-ds-amd64-6thzn
```
Name:               kube-flannel-ds-amd64-6thzn
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               k8sworker02/10.0.0.230
Start Time:         Tue, 14 May 2019 09:38:37 +0200
Labels:             app=flannel
                    controller-revision-hash=6d5d4fbf45
                    pod-template-generation=1
                    tier=node
Annotations:        <none>
Status:             Pending
IP:                 10.0.0.230
Controlled By:      DaemonSet/kube-flannel-ds-amd64
Init Containers:
  install-cni:
    Container ID:  
    Image:         quay.io/coreos/flannel:v0.11.0-amd64
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
    Args:
      -f
      /etc/kube-flannel/cni-conf.json
      /etc/cni/net.d/10-flannel.conflist
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/cni/net.d from cni (rw)
      /etc/kube-flannel/ from flannel-cfg (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from flannel-token-lg89q (ro)
Containers:
  kube-flannel:
    Container ID:  
    Image:         quay.io/coreos/flannel:v0.11.0-amd64
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/bin/flanneld
    Args:
      --ip-masq
      --kube-subnet-mgr
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:     100m
      memory:  50Mi
    Environment:
      POD_NAME:       kube-flannel-ds-amd64-6thzn (v1:metadata.name)
      POD_NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /etc/kube-flannel/ from flannel-cfg (rw)
      /run/flannel from run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from flannel-token-lg89q (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  run:
    Type:          HostPath (bare host directory volume)
    Path:          /run/flannel
    HostPathType:  
  cni:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  flannel-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-flannel-cfg
    Optional:  false
  flannel-token-lg89q:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  flannel-token-lg89q
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  beta.kubernetes.io/arch=amd64
Tolerations:     :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason                  Age                   From                  Message
  ----     ------                  ----                  ----                  -------
  Normal   Scheduled               60m                   default-scheduler     Successfully assigned kube-system/kube-flannel-ds-amd64-6thzn to k8sworker02
  Warning  FailedCreatePodSandBox  60m                   kubelet, k8sworker02  Failed create pod sandbox: rpc error: code = Unknown desc = `/usr/lib/cri-o-runc/sbin/runc start fd05c1ab2cf22796c7e3613ed696e7173c8a3192659006c178859ccc12f031de` failed: exit status 1
```

**Describe the results you expected:**
After joinging no errors: 
```
● crio.service - Open Container Initiative Daemon
   Loaded: loaded (/lib/systemd/system/crio.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-05-07 11:43:01 CEST; 6 days ago
     Docs: https://github.com/kubernetes-sigs/cri-o
 Main PID: 26175 (crio)
    Tasks: 15
   CGroup: /system.slice/crio.service
           └─26175 /usr/bin/crio

mei 07 11:43:01 k8smaster systemd[1]: Starting Open Container Initiative Daemon...
mei 07 11:43:01 k8smaster systemd[1]: Started Open Container Initiative Daemon.

```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.13.1-dev
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 18.04.2

**Comment by giuseppe** [comment] 2019-05-14 09:28
looks like the issue is already tracked here: https://github.com/kubernetes/kubernetes/issues/77615

**Comment by joost14** [comment] 2019-05-14 13:38
Hi @giuseppe 

Thx for the reply I'll have a look at it.

**Comment by sfxworks** [comment] 2019-05-14 16:16
Also getting this! Glad I found this.

**Comment by giuseppe** [comment] 2019-05-14 19:57
PR here: https://github.com/opencontainers/runc/pull/2057

**Comment by mrunalp** [comment] 2019-05-15 00:39
The upstream PR has been merged!

**Closed** 2019-05-15 00:39 UTC

**Comment by rhatdan** [comment] 2019-05-15 19:31
@lsm5 @jnovy Can we get new builds of runc prepared for RHEL7 and RHEL8
