### ISSUE TITLE
Version mismatch in Debian_11 repo

### ISSUE THREAD

**Issue by mbleichner** [cri-o/cri-o#5329] opened 2021-09-19 07:45 UTC
**Description**

When installing CRI-O via Debian_11 repository, apt reports installed version as `1.22.0~0`, but `crio --version` says `1.19.4`.

**Steps to reproduce the issue:**
1. Follow installation instructions with `OS=Debian_11`, `VERSION=1.22`
2. Check output of `apt show cri-o` and `crio --version`

**Describe the results you received:**

    $ apt show cri-o
    Package: cri-o
    Version: 1.22.0~0
    Priority: optional
    Section: devel
    Maintainer: Douglas Schilling Landgraf <dougsland@redhat.com>
    Installed-Size: 86,3 MB
    Depends: libgpgme11, libseccomp2, conmon, containers-common (>= 0.1.27), tzdata
    Suggests: cri-o-runc | runc (>= 1.0.0), containernetworking-plugins
    Replaces: cri-o-1.19, cri-o-1.20, cri-o-1.21
    Homepage: https://github.com/cri-o/cri-o
    Download-Size: 17,8 MB
    APT-Manual-Installed: yes
    APT-Sources: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/Debian_11  Packages
    Description: OCI-based implementation of Kubernetes Container Runtime Interface.

    $ crio --version
    crio version 1.19.4
    Version:       1.19.4
    GitCommit:     ea37eea44fbbde07115286071fb18bd839bedc3d
    GitTreeState:  clean
    BuildDate:     2021-09-17T19:31:48Z
    GoVersion:     go1.16.8
    Compiler:      gc
    Platform:      linux/amd64
    Linkmode:      dynamic

**Describe the results you expected:**

CRI-O version as reported by `crio --version` should be `1.22.x`

**Additional information you deem important (e.g. issue happens only occasionally):**

A few days ago it was possible to install 1.22 from Debian_Testing Repo, but now I get a 404 when doing `apt update`.

**Output of `crio --version`:** see above.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Self hosted KVM.

**Comment by utam0k** [comment] 2021-09-19 09:44
I've prepared a minimal command that can reproduce the problem in this issue. Please use this to solve this issue.
```console
$ docker run --rm -i debian:bullseye /bin/bash -s <<EOF                                                                                                                                                  [refactoring/test_framework] ~/ghq/github.com/utam0k/youki/test_framework utam0k
apt update && apt install -y curl gnupg
OS=Debian_11
VERSION=1.22
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key add -
apt update
apt install -y cri-o cri-o-runc
crio --version
EOF
```

**Comment by mbleichner** [comment] 2021-09-19 19:10
@utam0k `$` variables need to be escaped for this to work.

Alternatively, put the first `EOF` in single quotes (like `/bin/bash -s << 'EOF'`) to disable variable substitution in the heredoc.

**Comment by utam0k** [comment] 2021-09-22 14:08
@haircommander Is this issue possibly a duplicate of https://github.com/cri-o/cri-o/issues/5267?

**Comment by haircommander** [comment] 2021-09-22 17:27
this one is a bit different than that, as it looks like debian 11 cri-o 1.22 is built but is linking incorrectly or something

**Comment by haircommander** [comment] 2021-09-22 21:02
has the issue magically gone away? I am hitting a different issue (some size mismatch) that I'm hoping also magically goes away

**Comment by utam0k** [comment] 2021-09-23 05:25
@haircommander This issue still remains. When I've run the above commands, I've got the following output.
```
crio version 1.19.4
Version:       1.19.4
GitCommit:     ea37eea44fbbde07115286071fb18bd839bedc3d
GitTreeState:  clean
BuildDate:     2021-09-17T19:31:48Z
GoVersion:     go1.16.8
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Comment by haircommander** [comment] 2021-09-23 13:16
I found the issue! should be fixed, thanks for your patience

**Comment by utam0k** [comment] 2021-09-23 14:05
> I found the issue! should be fixed, thanks for your patience

@haircommander  there are any other beginner-friendly issues to investigate or bugs to fix, please let me know. I'm interested in contributing to this product ;)

**Comment by haircommander** [comment] 2021-09-23 14:23
> > I found the issue! should be fixed, thanks for your patience
> 
> @haircommander there are any other beginner-friendly issues to investigate or bugs to fix, please let me know. I'm interested in contributing to this product ;)

Love to hear it! PTAL at any of these https://github.com/cri-o/cri-o/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 and comment if any seem interesting, then I could assign you :)

**Comment by haircommander** [comment] 2021-09-23 15:55
I believe this is fixed as such I am closing. please reopen if you disagree

**Closed by haircommander** 2021-09-23 15:55 UTC
