### ISSUE TITLE
Fedora 32 / cri-o 1.18 ... service fails to start

### ISSUE THREAD

**Issue by mazzystr** [cri-o/cri-o#3711] opened 2020-05-01 16:31 UTC
I have a fresh install of Fedora 32 and cri-o 1.18.  crio fails to start at `systemctl enable --now crio`

**Steps to reproduce the issue:**
1.  Install Fedora 32 
2. Install crio per https://cri-o.io/
3. systemctl enable --now crio

**Describe the results you received:**
 # systemctl status crio --no-pager -l
● crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/usr/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2020-04-30 16:31:17 PDT; 12min ago
       Docs: https://github.com/cri-o/cri-o
    Process: 922 ExecStart=/usr/bin/crio $CRIO_CONFIG_OPTIONS $CRIO_RUNTIME_OPTIONS $CRIO_STORAGE_OPTIONS $CRIO_NETWORK_OPTIONS $CRIO_METRICS_OPTIONS (code=exited, status=1/FAILURE)
   Main PID: 922 (code=exited, status=1/FAILURE)
        CPU: 208ms

Apr 30 16:31:17 cube0 crio[922]: time="2020-04-30 16:31:17.508525817-07:00" level=info msg="AppArmor is disabled by the system or at CRI-O build-time"
Apr 30 16:31:17 cube0 crio[922]: time="2020-04-30 16:31:17.522845028-07:00" level=info msg="Found CNI network crio (type=bridge) at /etc/cni/net.d/100-crio-bridge.conf"
Apr 30 16:31:17 cube0 crio[922]: time="2020-04-30 16:31:17.533307816-07:00" level=info msg="Found CNI network 200-loopback.conf (type=loopback) at /etc/cni/net.d/200-loopback.conf"
Apr 30 16:31:17 cube0 crio[922]: time="2020-04-30 16:31:17.576317230-07:00" level=info msg="Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist"
Apr 30 16:31:17 cube0 crio[922]: time="2020-04-30 16:31:17.576341624-07:00" level=info msg="Update default CNI network name to crio"
Apr 30 16:31:17 cube0 crio[922]: time="2020-04-30 16:31:17.793353021-07:00" level=warning msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
Apr 30 16:31:17 cube0 crio[922]: time="2020-04-30 16:31:17.796965936-07:00" level=fatal msg="Version string empty"
Apr 30 16:31:17 cube0 systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
Apr 30 16:31:17 cube0 systemd[1]: crio.service: Failed with result 'exit-code'.
Apr 30 16:31:17 cube0 systemd[1]: Failed to start Container Runtime Interface for OCI (CRI-O).

**Describe the results you expected:**
● crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/usr/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
     Active: active (running) since fooor evvv aaaah

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried setting selinux to permissive.  systemctl restart yields same failure.

**Output of `crio --version`:**
```
[root@cube0 ~]# crio --version
crio version
Version:
GitCommit:
GitTreeState:
BuildDate:
GoVersion:     go1.14
Compiler:      gc
Platform:      linux/amd64
Linkmode:      unknown: `ldd crio` failed: ldd: ./crio: No such file or directory
  (exit status 1)
[root@cube0 ~]# which crio
/usr/bin/crio
[root@cube0 ~]# ldd /usr/bin/crio
	linux-vdso.so.1 (0x00007fffbc79d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1149e9c000)
	libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007f1149e4e000)
	libgpgme.so.11 => /lib64/libgpgme.so.11 (0x00007f1149dfc000)
	libassuan.so.0 => /lib64/libassuan.so.0 (0x00007f1149de6000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f1149dc2000)
	libdevmapper.so.1.02 => /lib64/libdevmapper.so.1.02 (0x00007f1149d64000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f1149d57000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1149b8d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f114d9f6000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f1149b60000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007f1149b36000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f11499f0000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f1149957000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f114994e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1149933000)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical ... HP EliteDesk Mini G2 (Intel Core i5 / 16 gig mem)

Bugzilla is [here](https://bugzilla.redhat.com/show_bug.cgi?id=1830159)

**Comment by haircommander** [comment] 2020-05-01 16:33
@dougsland PTAL

**Comment by dougsland** [comment] 2020-05-01 17:19
Duplicate of: https://github.com/cri-o/cri-o/issues/3684

**Comment by haircommander** [comment] 2020-05-01 17:20
@mazzystr can you try updating to the latest? It should be fixed already.

**Comment by mazzystr** [comment] 2020-05-01 17:31
I have latest installed...
```
# dnf module list cri-o
Last metadata expiration check: 2:32:39 ago on Fri 01 May 2020 07:56:14 AM PDT.
Fedora Modular 32 - x86_64
Name                                 Stream                                  Profiles                                Summary
cri-o                                1.11                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.13                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.15                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.16                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.17                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers

Fedora Modular 32 - x86_64 - Updates
Name                                 Stream                                  Profiles                                Summary
cri-o                                1.11                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.13                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.15                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.16                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.17                                    default                                 Kubernetes Container Runtime Interface for OCI-based containers
cri-o                                1.18 [e]                                default                                 Kubernetes Container Runtime Interface for OCI-based containers

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled

# rpm -qi cri-o
Name        : cri-o
Epoch       : 2
Version     : 1.18.0
Release     : 0.1.rc1.module_f32+8645+a8dc4c4b
Architecture: x86_64
Install Date: Thu 30 Apr 2020 03:57:03 PM PDT
Group       : Unspecified
Size        : 119177401
License     : ASL 2.0
Signature   : RSA/SHA256, Wed 15 Apr 2020 11:49:45 AM PDT, Key ID 6c13026d12c944d0
Source RPM  : cri-o-1.18.0-0.1.rc1.module_f32+8645+a8dc4c4b.src.rpm
Build Date  : Wed 15 Apr 2020 09:23:08 AM PDT
Build Host  : buildhw-10.phx2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/cri-o/cri-o
Bug URL     : https://bugz.fedoraproject.org/cri-o
Summary     : Kubernetes Container Runtime Interface for OCI-based containers
Description :
Kubernetes Container Runtime Interface for OCI-based containers
```

Still no dice getting cri-o to run...
```
# systemctl restart crio
Job for crio.service failed because the control process exited with error code.
See "systemctl status crio.service" and "journalctl -xe" for details.

# systemctl status crio.service -l --no-pager
● crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/usr/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2020-05-01 10:30:44 PDT; 2s ago
       Docs: https://github.com/cri-o/cri-o
    Process: 3546 ExecStart=/usr/bin/crio $CRIO_CONFIG_OPTIONS $CRIO_RUNTIME_OPTIONS $CRIO_STORAGE_OPTIONS $CRIO_NETWORK_OPTIONS $CRIO_METRICS_OPTIONS (code=exited, status=1/FAILURE)
   Main PID: 3546 (code=exited, status=1/FAILURE)
        CPU: 105ms

May 01 10:30:44 cube0 crio[3546]: time="2020-05-01 10:30:44.855565450-07:00" level=info msg="AppArmor is disabled by the system or at CRI-O build-time"
May 01 10:30:44 cube0 crio[3546]: time="2020-05-01 10:30:44.858929671-07:00" level=info msg="Found CNI network crio (type=bridge) at /etc/cni/net.d/100-crio-bridge.conf"
May 01 10:30:44 cube0 crio[3546]: time="2020-05-01 10:30:44.861709114-07:00" level=info msg="Found CNI network 200-loopback.conf (type=loopback) at /etc/cni/net.d/200-loopback.conf"
May 01 10:30:44 cube0 crio[3546]: time="2020-05-01 10:30:44.872324992-07:00" level=info msg="Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist"
May 01 10:30:44 cube0 crio[3546]: time="2020-05-01 10:30:44.872351040-07:00" level=info msg="Update default CNI network name to crio"
May 01 10:30:44 cube0 crio[3546]: time="2020-05-01 10:30:44.872972309-07:00" level=warning msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
May 01 10:30:44 cube0 crio[3546]: time="2020-05-01 10:30:44.875579650-07:00" level=fatal msg="Version string empty"
May 01 10:30:44 cube0 systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
May 01 10:30:44 cube0 systemd[1]: crio.service: Failed with result 'exit-code'.
May 01 10:30:44 cube0 systemd[1]: Failed to start Container Runtime Interface for OCI (CRI-O).
```

**Comment by dougsland** [comment] 2020-05-01 17:32
the rpm is only available via update-testing at this moment, soon should arrive to stable:

# dnf module enable cri-o:1.18
# dnf install cri-o --enablerepo=updates-testing-modular

**Comment by harche** [comment] 2020-05-04 10:04
@dougsland I was wondering how long would it take for the fixes to arrive to stable? I need to use those packages in my PR for k8s node tests, https://github.com/kubernetes/test-infra/pull/17014/files

**Comment by dougsland** [comment] 2020-05-04 13:01
> @dougsland I was wondering how long would it take for the fixes to arrive to stable? I need to use
>  those packages in my PR for k8s node tests, https://github.com/kubernetes/test
> -infra/pull/17014/files

Hey @harche ,
From my understanding, 3 more days to reach 7 days or 3 positives votes (karmas).

"FEDORA-MODULAR-2020-07c39c5893 created by dougsland **4 days ago** "
https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2020-07c39c5893

**Comment by kungfu71186** [comment] 2020-05-06 05:58
Looks good.

```
/usr/bin/crio -v
crio version
Version:       1.18.0
GitCommit:     7d79f42b28ad00cf2e7d86604a5a4007303ac328
GitTreeState:  clean
BuildDate:     2020-04-29T15:16:34Z
GoVersion:     go1.14.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```
```
● crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/usr/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2020-05-06 08:57:03 +03; 7s ago
       Docs: https://github.com/cri-o/cri-o
   Main PID: 344496 (crio)
      Tasks: 11
     Memory: 30.5M
        CPU: 94ms
     CGroup: /system.slice/crio.service
             └─344496 /usr/bin/crio

```

**Comment by mazzystr** [comment] 2020-05-06 21:09
Yup looks good to me also....
```
# rpm -qi cri-o-1.18.0-2.module_f32+8778+fdcfac52.x86_64
Name        : cri-o
Epoch       : 2
Version     : 1.18.0
Release     : 2.module_f32+8778+fdcfac52
Architecture: x86_64
Install Date: Wed 06 May 2020 01:17:14 PM PDT
Group       : Unspecified
Size        : 119199150
License     : ASL 2.0
Signature   : (none)
Source RPM  : cri-o-1.18.0-2.module_f32+8778+fdcfac52.src.rpm
Build Date  : Wed 29 Apr 2020 08:16:34 AM PDT
Build Host  : buildvm-07.phx2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/cri-o/cri-o
Bug URL     : https://bugz.fedoraproject.org/cri-o
Summary     : Kubernetes Container Runtime Interface for OCI-based containers
Description :
Kubernetes Container Runtime Interface for OCI-based containers

# crio version
Version:       1.18.0
GitCommit:     7d79f42b28ad00cf2e7d86604a5a4007303ac328
GitTreeState:  clean
BuildDate:     2020-04-29T15:16:34Z
GoVersion:     go1.14.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      unknown: `ldd /root/crio` failed: ldd: /root/crio: No such file or directory
  (exit status 1)

# systemctl status crio
● crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/usr/lib/systemd/system/crio.service; disabled; vendor preset: disabled)
     Active: active (running) since Wed 2020-05-06 13:37:08 PDT; 31min ago
       Docs: https://github.com/cri-o/cri-o
   Main PID: 21829 (crio)
      Tasks: 20
     Memory: 68.8M
     CGroup: /system.slice/crio.service
             ├─21829 /usr/bin/crio
             └─83291 /usr/libexec/cni/bridge
```

**Comment by mazzystr** [comment] 2020-05-06 21:15
This is a very sweet thing to see ...

```
]# minikube start --driver=none --container-runtime=cri-o
😄  minikube v1.9.2 on Fedora 32
✨  Using the none driver based on user configuration
❗  Using the 'cri-o' runtime with the 'none' driver is an untested configuration!
👍  Starting control plane node  in cluster minikube
🤹  Running on localhost (CPUs=4, Memory=15886MB, Disk=15350MB) ...
ℹ️  OS release is Fedora 32 (Server Edition)
🎁  Preparing Kubernetes v1.18.0 on CRI-O  ...
🌟  Enabling addons: default-storageclass, storage-provisioner
🤹  Configuring local host environment ...

❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl and minikube configuration will be stored in /root
❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🏄  Done! kubectl is now configured to use "minikube"

# crictl ps
CONTAINER ID        IMAGE                                                              CREATED             STATE               NAME                      ATTEMPT             POD ID
317c2387ea427       2c23f803037938fba3d7945ca014cabe6703724bce3d57b89e02261d4d8d59b5   1 second ago        Running             compute                   0                   ad8c9cb9b805c
0d0ecf341836d       065be83d7902240eeeb1f38aec738a2800bf7448119825129cab201e248da493   33 minutes ago      Running             virt-handler              0                   d2c0b5fb1542c
a036402df918c       7ac953a7e2dba04d78c90fb16e7b43c084d391e2a930e72fc06153bdfda9a000   33 minutes ago      Running             virt-controller           0                   7cfb1bd3ea676
3cb6d24f3d077       7ac953a7e2dba04d78c90fb16e7b43c084d391e2a930e72fc06153bdfda9a000   33 minutes ago      Running             virt-controller           0                   3cb24a6ddbac8
e7f7e8aff658b       74ce0f153eb2e6487ac469a9cb54185b5aadd87a1573576cb2f7b195d4ba6f50   33 minutes ago      Running             virt-api                  0                   709c7ae32b70c
5943d8929d67f       74ce0f153eb2e6487ac469a9cb54185b5aadd87a1573576cb2f7b195d4ba6f50   33 minutes ago      Running             virt-api                  0                   c5477b30281e6
fb5167f19091c       3ef07a3d300d7e2ed6e4b617271e65ba93383e32153e754353b7ff806a762e81   33 minutes ago      Running             virt-operator             0                   308b2d7de3966
5658b256707f0       3ef07a3d300d7e2ed6e4b617271e65ba93383e32153e754353b7ff806a762e81   33 minutes ago      Running             virt-operator             0                   78e734c7d2f1d
8e5d127626a7d       4689081edb103a9e8174bf23a255bfbe0b2d9ed82edc907abab6989d1c60f02c   36 minutes ago      Running             storage-provisioner       0                   2f2526a66d225
bee7c61112efa       67da37a9a360e600e74464da48437257b00a754c77c40f60c65e4cb327c34bd5   36 minutes ago      Running             coredns                   0                   070f9f2d2b73f
8071d1e77d122       67da37a9a360e600e74464da48437257b00a754c77c40f60c65e4cb327c34bd5   36 minutes ago      Running             coredns                   0                   c5c9d6e16a953
400d8bd3384cf       43940c34f24f39bc9a00b4f9dbcab51a3b28952a7c392c119b877fcb48fe65a3   36 minutes ago      Running             kube-proxy                0                   cead10d7c97b4
d34aa17983ac3       303ce5db0e90dab1c5728ec70d21091201a23cdf8aeca70ab54943bbaaf0833f   36 minutes ago      Running             etcd                      0                   393d4f8ca74bc
2d54297c5c1b1       a31f78c7c8ce146a60cc178c528dd08ca89320f2883e7eb804d7f7b062ed6466   36 minutes ago      Running             kube-scheduler            0                   52a785d3b07b9
21305f0dc242d       74060cea7f70476f300d9f04fe2c3b3a2e84589e0579382a8df8c82161c3735c   36 minutes ago      Running             kube-apiserver            0                   63ff45628acf0
5cca8b426bbe8       d3e55153f52fb62421dae9ad1a8690a3fd1b30f1b808e50a69a8e7ed5565e72e   36 minutes ago      Running             kube-controller-manager   0                   118203a97f0dd

# kubectl get nodes
NAME    STATUS   ROLES    AGE   VERSION
cube0   Ready    master   38m   v1.18.0
```

**Comment by dougsland** [comment] 2020-05-06 21:17
> This is a very sweet thing to see ...
> 
> ```
> # minikube start --driver=none --container-runtime=cri-o
> 😄  minikube v1.9.2 on Fedora 32
> ✨  Using the none driver based on user configuration
> ❗  Using the 'cri-o' runtime with the 'none' driver is an untested configuration!
> 👍  Starting control plane node  in cluster minikube
> 🤹  Running on localhost (CPUs=4, Memory=15886MB, Disk=15350MB) ...
> ℹ️  OS release is Fedora 32 (Server Edition)
> 🎁  Preparing Kubernetes v1.18.0 on CRI-O  ...
> 🌟  Enabling addons: default-storageclass, storage-provisioner
> 🤹  Configuring local host environment ...
> 
> ❗  The 'none' driver is designed for experts who need to integrate with an existing VM
> 💡  Most users should use the newer 'docker' driver instead, which does not require root!
> 📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/
> 
> ❗  kubectl and minikube configuration will be stored in /root
> ❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:
> 
>     ▪ sudo mv /root/.kube /root/.minikube $HOME
>     ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube
> 
> 💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
> 🏄  Done! kubectl is now configured to use "minikube"
> 
> # crictl ps
> CONTAINER ID        IMAGE                                                              CREATED             STATE               NAME                      ATTEMPT             POD ID
> 317c2387ea427       2c23f803037938fba3d7945ca014cabe6703724bce3d57b89e02261d4d8d59b5   1 second ago        Running             compute                   0                   ad8c9cb9b805c
> 0d0ecf341836d       065be83d7902240eeeb1f38aec738a2800bf7448119825129cab201e248da493   33 minutes ago      Running             virt-handler              0                   d2c0b5fb1542c
> a036402df918c       7ac953a7e2dba04d78c90fb16e7b43c084d391e2a930e72fc06153bdfda9a000   33 minutes ago      Running             virt-controller           0                   7cfb1bd3ea676
> 3cb6d24f3d077       7ac953a7e2dba04d78c90fb16e7b43c084d391e2a930e72fc06153bdfda9a000   33 minutes ago      Running             virt-controller           0                   3cb24a6ddbac8
> e7f7e8aff658b       74ce0f153eb2e6487ac469a9cb54185b5aadd87a1573576cb2f7b195d4ba6f50   33 minutes ago      Running             virt-api                  0                   709c7ae32b70c
> 5943d8929d67f       74ce0f153eb2e6487ac469a9cb54185b5aadd87a1573576cb2f7b195d4ba6f50   33 minutes ago      Running             virt-api                  0                   c5477b30281e6
> fb5167f19091c       3ef07a3d300d7e2ed6e4b617271e65ba93383e32153e754353b7ff806a762e81   33 minutes ago      Running             virt-operator             0                   308b2d7de3966
> 5658b256707f0       3ef07a3d300d7e2ed6e4b617271e65ba93383e32153e754353b7ff806a762e81   33 minutes ago      Running             virt-operator             0                   78e734c7d2f1d
> 8e5d127626a7d       4689081edb103a9e8174bf23a255bfbe0b2d9ed82edc907abab6989d1c60f02c   36 minutes ago      Running             storage-provisioner       0                   2f2526a66d225
> bee7c61112efa       67da37a9a360e600e74464da48437257b00a754c77c40f60c65e4cb327c34bd5   36 minutes ago      Running             coredns                   0                   070f9f2d2b73f
> 8071d1e77d122       67da37a9a360e600e74464da48437257b00a754c77c40f60c65e4cb327c34bd5   36 minutes ago      Running             coredns                   0                   c5c9d6e16a953
> 400d8bd3384cf       43940c34f24f39bc9a00b4f9dbcab51a3b28952a7c392c119b877fcb48fe65a3   36 minutes ago      Running             kube-proxy                0                   cead10d7c97b4
> d34aa17983ac3       303ce5db0e90dab1c5728ec70d21091201a23cdf8aeca70ab54943bbaaf0833f   36 minutes ago      Running             etcd                      0                   393d4f8ca74bc
> 2d54297c5c1b1       a31f78c7c8ce146a60cc178c528dd08ca89320f2883e7eb804d7f7b062ed6466   36 minutes ago      Running             kube-scheduler            0                   52a785d3b07b9
> 21305f0dc242d       74060cea7f70476f300d9f04fe2c3b3a2e84589e0579382a8df8c82161c3735c   36 minutes ago      Running             kube-apiserver            0                   63ff45628acf0
> 5cca8b426bbe8       d3e55153f52fb62421dae9ad1a8690a3fd1b30f1b808e50a69a8e7ed5565e72e   36 minutes ago      Running             kube-controller-manager   0                   118203a97f0dd
> 
> # kubectl get nodes
> NAME    STATUS   ROLES    AGE   VERSION
> cube0   Ready    master   38m   v1.18.0
> ```

@mazzystr  Indeed, very good. :)  Please also take a look in this one: https://github.com/cri-o/cri-o/tree/master/contrib/kube-local  (Not related to this thread, by anyway) :+1:

**Comment by dougsland** [comment] 2020-05-08 13:21
@mazzystr @harche @haircommander  the latest bits are in the stable channel. Please consider closing this ticket. Thanks!

# cat /etc/fedora-release 
Fedora release 32 (Thirty Two)

# dnf module info cri-o:1.18
Last metadata expiration check: 0:34:42 ago on Fri 08 May 2020 08:44:59 AM EDT.
Name             : cri-o
Stream           : 1.18 [e] [a]
Version          : 3220200429145402
Context          : 43bbeeef
Architecture     : x86_64
Profiles         : default
Default profiles : 
Repo             : updates-modular
Summary          : Kubernetes Container Runtime Interface for OCI-based containers
Description      : CRI-O is the Kubernetes Container Runtime Interface for OCI-based containers.
Requires         : platform:[f32]
Artifacts        : cri-o-2:1.18.0-2.module_f32+8778+fdcfac52.src
                 : cri-o-2:1.18.0-2.module_f32+8778+fdcfac52.x86_64
                 : cri-o-debuginfo-2:1.18.0-2.module_f32+8778+fdcfac52.x86_64
                 : cri-o-debugsource-2:1.18.0-2.module_f32+8778+fdcfac52.x86_64

**Closed** 2020-05-08 13:38 UTC

**Comment by mazzystr** [comment] 2020-05-08 15:27
Confirmed.  cri-o is now very boring ... just the way we like it!  :)
```
[root@cube0 ~]# yum install cri-o
Fedora 32 openh264 (From Cisco) - x86_64                                                                                                                                           3.5 kB/s | 5.1 kB     00:01
Fedora Modular 32 - x86_64                                                                                                                                                         2.0 MB/s | 4.9 MB     00:02
Fedora Modular 32 - x86_64 - Updates                                                                                                                                               618 kB/s | 1.4 MB     00:02
Fedora 32 - x86_64 - Updates                                                                                                                                                       5.2 MB/s | 8.2 MB     00:01
Fedora 32 - x86_64                                                                                                                                                                  18 MB/s |  70 MB     00:03
Kubernetes                                                                                                                                                                         101 kB/s |  91 kB     00:00
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                 Architecture                             Version                                                                  Repository                                         Size
===================================================================================================================================================================================================================
Installing:
 cri-o                                   x86_64                                   2:1.18.0-2.module_f32+8778+fdcfac52                                      updates-modular                                    26 M

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total download size: 26 M
Installed size: 114 M
Is this ok [y/N]: y
Downloading Packages:
cri-o-1.18.0-2.module_f32+8778+fdcfac52.x86_64.rpm                                                                                                                                  12 MB/s |  26 MB     00:02
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                              9.7 MB/s |  26 MB     00:02
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1
  Installing       : cri-o-2:1.18.0-2.module_f32+8778+fdcfac52.x86_64                                                                                                                                          1/1
  Running scriptlet: cri-o-2:1.18.0-2.module_f32+8778+fdcfac52.x86_64                                                                                                                                          1/1
  Verifying        : cri-o-2:1.18.0-2.module_f32+8778+fdcfac52.x86_64                                                                                                                                          1/1

Installed:
  cri-o-2:1.18.0-2.module_f32+8778+fdcfac52.x86_64

Complete!
[root@cube0 ~]# systemctl start crio
[root@cube0 ~]# ps -ef | grep crio
root     2896327       1  0 08:26 ?        00:00:00 /usr/bin/crio
```

**Comment by haircommander** [comment] 2020-05-08 15:41
excellent to hear, thanks for the reports and patience folks!

**Comment by rhatdan** [comment] 2020-05-08 18:32
Boring is good.  I always say CRI-O should be like a file system, it just does it's job, and I should seldom need to think about it.

**Comment by mazzystr** [comment] 2020-05-08 19:33
Do we know why we were failing here?  `--log-level debug` and `strace` didn't help pinpoint the problem.

**Comment by kungfu71186** [comment] 2020-05-08 19:48
@mazzystr the error isn't obvious because it's a really wierd error you wouldn't expect, but it's literally because the version wasn't set. It does show the fatal error in the log though.

**Comment by dougsland** [comment] 2020-05-08 19:48
Hi,

> Do we know why we were failing here? `--log-level debug` and `strace` didn't help pinpoint the
> problem.

Yes, the version string was empty, from the logs:
```
Apr 30 16:31:17 cube0 crio[922]: time="2020-04-30 16:31:17.796965936-07:00" level=fatal msg="Version string empty"
```

```
During the build CRI-O uses -X to set some values that were not shipping inside the RPM.
Here the full patch inside Fedora packaging:

```
$ git show 6ee7c76731cbb141d9929ac0a0952dd85b7f8bb2
commit 6ee7c76731cbb141d9929ac0a0952dd85b7f8bb2
Author: Douglas Schilling Landgraf <dougsland@redhat.com>
Date:   Wed Apr 29 10:25:22 2020 -0400

    build: include version data during the build
    
    Resolves: github.com/cri-o/cri-o/issues/3684

diff --git a/cri-o.spec b/cri-o.spec
index 62d5156..eb3372e 100644
--- a/cri-o.spec
+++ b/cri-o.spec
@@ -16,16 +16,26 @@
 %define gobuild(o:) GO111MODULE=off go build -buildmode pie -compiler gc -tags="rpm_crashtraceback ${BUILDTAGS:-}" -ldflags "${LDFLAGS:-} -B 0x$(head -c20 /dev/urandom|od -An -tx1|tr -d ' \\n') -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '" -a -v -x %{?**}; 
 %endif
 
+# Global vars
 %global provider github
 %global provider_tld com
 %global project cri-o
 %global repo cri-o
+
+# Related: github.com/cri-o/cri-o/issues/3684
+%global build_timestamp %(date -u +'%Y-%m-%dT%H:%M:%SZ')
+%global git_tree_state clean
+%global criocli_path ""
+
 # https://github.com/cri-o/cri-o
 %global import_path %{provider}.%{provider_tld}/%{project}/%{repo}
+
+# Commit for the builds
 %global commit0 7d79f42b28ad00cf2e7d86604a5a4007303ac328
 %global shortcommit0 %(c=%{commit0}; echo ${c:0:7})
 %global git0 https://%{import_path}
 
+# Services
 %global service_name crio
 
 # Used for comparing with latest upstream tag
@@ -100,6 +110,15 @@ ln -s vendor src
 export GOPATH=$(pwd)/_output:$(pwd)
 export BUILDTAGS="$(hack/btrfs_installed_tag.sh) $(hack/btrfs_tag.sh) $(hack/libdm_installed.sh) $(hack/libdm_no_deferred_remove_tag.sh) $(hack/seccomp_tag.sh) $(hack/selinux_tag.sh)"
 export GO111MODULE=off
+
+# Related: github.com/cri-o/cri-o/issues/3684
+export LDFLAGS="-X %{import_path}/internal/pkg/criocli.DefaultsPath=%{criocli_path}
+-X  %{import_path}/internal/version.buildDate=%{build_timestamp}
+-X  %{import_path}/internal/version.gitCommit=%{commit0}
+-X  %{import_path}/internal/version.version=%{version}
+-X  %{import_path}/internal/version.gitTreeState=%{git_tree_state}"
+
 %gobuild -o bin/%{service_name} %{import_path}/cmd/%{service_name}
 %gobuild -o bin/%{service_name}-status %{import_path}/cmd/%{service_name}-status
 

```

**Comment by mazzystr** [comment] 2020-05-08 20:00
@dougsland Thanks for that excellent explanation!
