### ISSUE TITLE
CentOS 8 installation broken from official documentation

### ISSUE THREAD

**Issue by petebuffon** [cri-o/cri-o#3922] opened 2020-07-02 00:53 UTC
I can't seem to install cri-o on CentOS 8 from the official documentation.  I also encountered a new issue while trying the fix from #3776 with a fresh CentOS 8 VM.  I first ran:

```
dnf -y module disable container-tools
dnf -y install 'dnf-command(copr)'
dnf -y copr enable rhcontainerbot/container-selinux
cd /etc/yum.repos.d/
curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo
wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.18/CentOS_8/devel:kubic:libcontainers:stable:cri-o:1.18.repo
```

Then cri-o wouldn't install because criu isn't available from the appstream anymore:

```
sudo dnf install cri-o
Last release available in 1.18 branch (CentOS_8 1.7 kB/s | 3.3 kB     00:01    
Error: 
 Problem: package cri-o-2:1.18.2-2.2.el8.x86_64 requires runc >= 1.0.0-16, but none of the providers can be installed
  - package runc-1.0.0-103.dev.el8.x86_64 requires criu, but none of the providers can be installed
  - conflicting requests
  - package criu-3.12-9.module_el8.2.0+303+1105185b.x86_64 is filtered out by modular filtering
  - package criu-3.12-9.module_el8.2.0+304+65a3c2ac.x86_64 is filtered out by modular filtering
  - package criu-3.12-9.module_el8.2.0+305+5e198a41.x86_64 is filtered out by modular filtering
  - package runc-1.0.0-56.rc5.dev.git2abd837.module_el8.2.0+303+1105185b.x86_64 is filtered out by modular filtering
  - package runc-1.0.0-64.rc10.module_el8.2.0+304+65a3c2ac.x86_64 is filtered out by modular filtering
  - package runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64 is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

I expected cri-o to install without any further steps.  Is there another repo that needs to be enabled or is there a simpler solution that can be implemented?

I got around the issue by following the official documentation:

```
sudo dnf -y install 'dnf-command(copr)'
sudo dnf -y copr enable rhcontainerbot/container-selinux
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION].repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION]/CentOS_8/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION].repo
sudo dnf -y install cri-o
```

And then changing one line in /etc/crio/crio.conf:

```
sed -i 's|conmon = "/usr/libexec/crio/conmon"|conmon = "/usr/bin/conmon"|g' /etc/crio/crio.conf
```
cri-o now runs without issue.

output of crio --version:

```
crio version 1.18.2
Version:       1.18.2
GitCommit:     7f261aeebffed079b4475dde8b9d602b01973d33
GitTreeState:  clean
BuildDate:     2020-07-01T04:15:18Z
GoVersion:     go1.13.4
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Comment by kallisti5** [comment] 2020-07-10 13:57
Ran into same issue on CentOS 8. This fixed it for me!

**Comment by fidencio** [comment] 2020-07-24 06:12
This one looks like a duplicate of #3818, which is a duplicate of #3776.
If that's the case, please, consider closing this issue.

**Closed** 2020-07-28 23:41 UTC
