### ISSUE TITLE
release-1.15 build fails on 32-bit

### ISSUE THREAD

**Issue by lsm5** [cri-o/cri-o#2712] opened 2019-08-10 19:30 UTC
```# github.com/cri-o/cri-o/vendor/github.com/containers/libpod/libpod
src/github.com/cri-o/cri-o/vendor/github.com/containers/libpod/libpod/stats.go:90:17: invalid operation: cgroupLimit > physicalLimit (mismatched types uint64 and uint32)
src/github.com/cri-o/cri-o/vendor/github.com/containers/libpod/libpod/stats.go:91:3: cannot use physicalLimit (type uint32) as type uint64 in return argument```

**Comment by lsm5** [comment] 2019-08-10 19:32
@haircommander @mrunalp @saschagrunert @umohnani8

**Comment by lsm5** [comment] 2019-08-10 19:32
here's the fail log from ubuntu ppa: https://launchpadlibrarian.net/436825048/buildlog_ubuntu-xenial-armhf.cri-o-1.15_1.15.1-1~dev~ubuntu16.04~ppa2_BUILDING.txt.gz

**Comment by saschagrunert** [comment] 2019-08-12 06:55
Hey @lsm5 :wave: . So I think we should add another 32bit test to check that everything works as intended. :thinking:

**Comment by haircommander** [comment] 2019-08-13 15:53
closing per #2718 merge

**Closed by haircommander** 2019-08-13 15:53 UTC
