### ISSUE TITLE
[cgroupfs] crio-conmon- sub-cgroup handling

### ISSUE THREAD

**Issue by runcom** [cri-o/cri-o#838] opened 2017-09-05 14:24 UTC
Current code in master have a leak https://github.com/kubernetes-incubator/cri-o/blob/master/oci/oci.go#L205 - the conmon cgroup isn't never deleted actually. ~~I'm removing that here though https://github.com/kubernetes-incubator/cri-o/pull/814/commits/5779d5243ac2d9abdc05c627e49e6d2ff21ad832~~

We need to have conmon join with a sub-cgroup the pod's cgroup (we can't just join the pod's cgroup).
Right now, we do this with systemd by starting a transient slice which gets deleted after conmon exits.
We need to find a way to monitor conmon and delete its sub-cgroup once it exits.

@mrunalp @derekwaynecarr

**Comment by runcom** [comment] 2017-09-05 14:26
@derekwaynecarr you told me kubelet should take care of removing the pod's cgroup and all its sub-cgruop. Unfortunately this is not the case. If you run with cgroupfs on latest master you can see cgroup from crio-conmon- leaking around if you kill the kubelet/CRI-O.

**Comment by mrunalp** [comment] 2017-09-05 14:44
I think it would be best if kubelet does this cleanup as part of pod cgroup cleanup.

**Comment by runcom** [comment] 2017-09-05 14:50
> I think it would be best if kubelet does this cleanup as part of pod cgroup cleanup.

it should do that, but the only cgroup left from pod cgroup is the crio-conmon one (which is leaking...)

**Comment by runcom** [comment] 2017-09-05 14:56
so, kubelet is behaving correctly actually, it removes all cgroups from pod's cgroup parent.
The issue comes when you stop CRI-O, stop kube, and run "runc delete" on pods/containers. Everything will be cleaned up except crio-conmon-

**Comment by rhatdan** [comment] 2018-03-16 18:12
@runcom Can we close this issue?

**Comment by paulnivin** [comment] 2018-10-05 16:45
We're seeing this issue with an up to date cri-o build on release-1.10 with Kubernetes 1.10.8. We occasionally end up with Pods stuck looping with CreateContainerError leaking a cgroup containing conmon. Eventually, enough conmon cgroups are leaked to invoke the OOM killer, killing conmon and causing other issues with the node.  We're switching over to the systemd cgroup manager to see if that works around this issue.

**Comment by runcom** [comment] 2018-10-05 17:45
Thanks for the report, we'll try to find a solution for that but we aim at the kubelet to help us on that

**Comment by rhatdan** [comment] 2019-03-18 19:12
@runcom What's the skoop on this one?    Is this something we need people to work on?

**Comment by paulnivin** [comment] 2019-03-18 19:21
Moving to the systemd cgroup manager mitigated this issue for us.

**Comment by jpeach** [comment] 2019-07-01 06:24
I just debugged this problem and then found this issue. I can trivially reproduce with a pod that has `restartPolicy=Always` and a very short lifespan. After a few days, you'll get a few thousand leakes cgroups and the kubelet will stop responding.

At minimum, I don't think that `cgroupfs` should be the default.

**Comment by rhatdan** [comment] 2019-07-01 09:43
@vrothberg Could you take a look at this?

**Comment by vrothberg** [comment] 2019-07-01 09:56
@rhatdan, I am not sure I can help on that other than changing the default to systemd. @haircommander @umohnani8 @saschagrunert WDYT?

**Comment by jpeach** [comment] 2019-07-01 10:03
FWIW I'm going to switch over to the system driver too.

**Comment by vrothberg** [comment] 2019-07-01 10:07
> I just debugged this problem and then found this issue. I can trivially reproduce with a pod that has `restartPolicy=Always` and a very short lifespan. After a few days, you'll get a few thousand leakes cgroups and the kubelet will stop responding.

This sounds quite different to the initial description which stated that cgroups leak when CRI-O or/and the Kubelet are being stopped or killed. The upper description implies CRI-O leaks per se.

**Comment by vrothberg** [comment] 2019-07-01 10:31
I need to check CRI's logic a bit more but Podman is able to do that (Cc @mheon)

**Comment by jpeach** [comment] 2019-07-01 11:04
> On Jul 1, 2019, at 8:07 PM, Valentin Rothberg <notifications@github.com> wrote:
> 
> I just debugged this problem and then found this issue. I can trivially reproduce with a pod that has restartPolicy=Always and a very short lifespan. After a few days, you'll get a few thousand leakes cgroups and the kubelet will stop responding.
> 
> This sounds quite different to the initial description which stated that cgroups leak when CRI-O or/and the Kubelet are being stopped or killed. The upper description implies CRI-O leaks per se.

True. My experience sounds a lot like what @paulnivin describes, though I’m not sure whether this is still the same case that @runcom reported originally. We do restart kubelet at intervals due to puppet runs, but I was able to repro without that.

**Comment by vrothberg** [comment] 2019-07-01 12:03
I think we can fix it :^)

**Comment by vrothberg** [comment] 2019-07-01 12:24
Alright, I did some detailed analysis and CRI-O doesn't clean up the cgroups at all. We can follow libpod's example and reuse the `cgroups` package that has recently been added by @giuseppe.

@giuseppe @mheon, anything I might miss before I start getting my hands dirty in the code?

**Comment by mheon** [comment] 2019-07-01 12:53
Cgroupfs deletion was the cause of a persistent and nasty Podman test flake, so I was mucking around in it somewhat recently. Our issue might have been specific to the Libpod hierarchy (we put conmon in a sub-cgroup of the main pod cgroup, and then have conmon spawn further processes to clean up after containers die), but I would recommend setting the PIDs limit for cgroups you're removing to 1 before killing any remaining processes and removing the cgroup. Ref: https://github.com/containers/libpod/blob/master/libpod/runtime_pod_linux.go#L185-L216

**Closed** 2019-07-13 10:11 UTC
