### ISSUE TITLE
cri-o 1.17.5 runc not found in $PATH

### ISSUE THREAD

**Issue by steled** [cri-o/cri-o#4177] opened 2020-09-08 20:22 UTC
**Description**

**Steps to reproduce the issue:**
1. install cri-o according to the instructions: https://github.com/cri-o/cri-o/blob/master/install.md#apt-based-operating-systems
2. start cri-o

**Describe the results you received:**
```
sudo journalctl -xe
Sep 08 19:36:51 master01 systemd[1]: Starting Container Runtime Interface for OCI (CRI-O)...
-- Subject: A start job for unit crio.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit crio.service has begun execution.
--
-- The job identifier is 2334.
Sep 08 19:36:51 master01 crio[13077]: time="2020-09-08 19:36:51.556067963+02:00" level=fatal msg="runtime config: runtime validation: \"runc\" not found in $PATH: exec: \"runc\": executable file not found in $PATH"
Sep 08 19:36:51 master01 systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit crio.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Sep 08 19:36:51 master01 systemd[1]: crio.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit crio.service has entered the 'failed' state with result 'exit-code'.
Sep 08 19:36:51 master01 systemd[1]: Failed to start Container Runtime Interface for OCI (CRI-O).
-- Subject: A start job for unit crio.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit crio.service has finished with a failure.
--
-- The job identifier is 2334 and the job result is failed.
```

**Describe the results you expected:**
- normal start and use of `cri-o` with `cri-o-runc`

**Additional information you deem important (e.g. issue happens only occasionally):**
```
sudo less /etc/crio/crio.conf
[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"

sudo apt search cri-o
cri-o/unknown,now 1.17.5~1 amd64 [installed]
  OCI-based implementation of Kubernetes Container Runtime Interface.

sudo apt search cri-o-runc
cri-o-runc/unknown 1.0.0-6 armhf
  Open Container Project - runtime

sudo apt-get install cri-o-runc
cri-o-runc is already the newest version (1.0.0-6).
```

**Output of `crio --version`:**

```
crio -v
crio version 1.17.5
commit: "251a47ba0930c28e83dea8d409b79f568dd711aa-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- virtual environment with 
```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by haircommander** [comment] 2020-09-08 21:08
ah by "distrobutions runc" I meant the one if you do `apt install runc`. That will put runc in the $PATH. can you try that, instead of installing crio-runc?

**Comment by steled** [comment] 2020-09-09 13:43
Ok I installed `runc` via `apt-get install runc` and `crio` seem to work now...

```
sudo which runc
/usr/sbin/runc

sudo runc -v
runc version 1.0.0~rc6+dfsg1
commit: 1.0.0~rc6+dfsg1-3
spec: 1.0.1
```

But I thought that `runc` from Debian packaged version isn't needed when I install `cri-o-runc` as described at the `Note` at https://github.com/cri-o/cri-o/blob/master/install.md#apt-based-operating-systems

**Comment by haircommander** [comment] 2020-09-09 14:10
we used to have crio-runc the default value in the crio config. I must have inadvertently changed that...

I think, going forward, we should not rely on crio-runc, and instead install from the distribution. I will work on updating the other branches as they each release new versions

**Comment by steled** [comment] 2020-09-09 18:09
ok, sounds good...
so for me this problem is solved :-) 

thank you very much for your support

**Comment by steled** [comment] 2020-09-09 18:32
just for documentation purpose...


it seems that the part `cgroup_manager` at file `/etc/crio/crio.conf` changed:

```
cgroup_manager = "cgroupfs"
```

I added at the file `/var/lib/kubelet/config.yaml` the configuration `cgroupDriver: systemd`
so I also had to change the value at  `/etc/crio/crio.conf` from `cgroupfs` to `systemd`

without this I get the following error at pod creation:

```
Failed to create pod sandbox: rpc error: code = Unknown desc = cri-o configured with cgroupfs cgroup manager, but received systemd slice as parent
```

**Comment by haircommander** [comment] 2020-09-09 18:43
I found the issue, the build target changed upstream, but the downstream packaging script wasn't updated to reflect that. It should be updated now

**Comment by haircommander** [comment] 2020-09-09 18:44
(builds are building, I'll close this when I verify the change worked)

**Comment by Quarky9** [comment] 2020-09-09 19:20
@haircommander getting 
Err:1 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.17/xUbuntu_20.04  cri-o 1.17.5~1
  File has unexpected size (20669972 != 20667640). Mirror sync in progress? [IP: 195.135.221.134 80]
  Hashes of expected file:
   - SHA256:007a26f40a45479d2afdda015b43db372fb52f640363a5bfa7335b205618fc32
   - SHA1:062b080a027483974a4b630652e1cce9d22c8274 [weak]
   - MD5Sum:b8c85166a688ae7b4f1ec180c5a3a2d6 [weak]
   - Filesize:20667640 [weak]
E: Failed to fetch http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.17/xUbuntu_20.04/./amd64/cri-o_1.17.5~1_amd64.deb  File has unexpected size (20669972 != 20667640). Mirror sync in progress? [IP: 195.135.221.134 80]
   Hashes of expected file:
    - SHA256:007a26f40a45479d2afdda015b43db372fb52f640363a5bfa7335b205618fc32
    - SHA1:062b080a027483974a4b630652e1cce9d22c8274 [weak]
    - MD5Sum:b8c85166a688ae7b4f1ec180c5a3a2d6 [weak]
    - Filesize:20667640 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Since like 30 minutes ago ... timestamps of the package itself and the metadata are different at http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.17/xUbuntu_20.04/

**Comment by haircommander** [comment] 2020-09-09 19:26
@Quarky9 I just tried and didn't get that error, maybe clean up `/etc/apt/sources.list.d/devel:kubic...` and try again?

**Comment by haircommander** [comment] 2020-09-09 19:26
also @steled the issue should be resolved now, PTAL

**Comment by Quarky9** [comment] 2020-09-09 19:32
@haircommander Thx for quick update ... works now after cleaning out my apt cache. Seems like race condition. All good. Thx

**Comment by haircommander** [comment] 2020-09-09 19:53
happy to help :smile:

**Comment by steled** [comment] 2020-09-09 21:10
@haircommander it seems to work for Debian release... thank you for your support

I wrote something at #3233 I can't reopen the issue...
it seems that there is no `crio` binary...

**Comment by steled** [comment] 2020-09-10 17:31
@haircommander just for verification... 
`Debian_Testing` with `cri-o 1.17.5` and `cri-o-runc` works...
great job and thank you again...

now only `Raspbian_10` is left 🙈

**Comment by haircommander** [comment] 2020-09-10 18:01
yeah Rasbian is going to be a bit difficult, but I will work when I can. do you have a time frame you'd like the support by (I know you're in a dev env right now)

**Comment by haircommander** [comment] 2020-09-10 18:01
closing this as the issue is resolved

**Closed by haircommander** 2020-09-10 18:01 UTC

**Comment by steled** [comment] 2020-09-10 18:08
@haircommander maybe it would be great if Raspbian could work in the next 4 weeks?
maybe we can track the status at #3233 ?
