### ISSUE TITLE
Unexpected behavior with empty seccomp profile

### ISSUE THREAD

**Issue by benclarkwood** [cri-o/cri-o#3079] opened 2020-01-07 22:50 UTC
**Description**

When running cri-o with seccomp enabled, and a default profile specified, the runtime falls back to "unconfined" when no profile is specified.

**Steps to reproduce the issue:**
1. Enable seccomp
2. Specify a default profile
3. Create a Pod

**Describe the results you received:**
Empty profile default to `unconfined`

**Describe the results you expected:**
Empty profile defaulting to `runtime/default`

**Output of `crio --version`:**
1.14.9

**Comment by saschagrunert** [comment] 2020-01-08 10:17
Hey @benclarkwood, thank you for opening the issue. As already discussed I will assign the issue to you since you've state that you'd be happy to work on this issue.

I took my time to play around with seccomp and AppArmor profiles and would expect the same as described by @benclarkwood. Generally it was not possible for me to find any generalized description of:

- If a profile is specified to a pod, it applies to all containers as well
- If a profile is specified to a container, it overwrites the pods profile
- We always default to `runtime/default`

I really would like to enforce this from a security perspective and document it properly in a dedicated security section inside this repository. WDYT?

**Comment by saschagrunert** [comment] 2020-01-08 11:36
I proposed the change for AppArmor here: https://github.com/cri-o/cri-o/pull/3083

**Comment by haircommander** [comment] 2020-04-29 20:04
as we've seen [here](https://github.com/cri-o/cri-o/pull/3342) this is actually expected behavior, and is an invariant of the CRI. As such, it is not a problem in CRI-O. What do you think about closing this issue and opening one to track in upstream kube @benclarkwood

**Comment by haircommander** [comment] 2020-08-04 14:55
@saschagrunert would the upstream seccomp work fix this issue? i.e: are we targeting a non-empty default profile for 1.19 or 1.20?

**Comment by saschagrunert** [comment] 2020-08-05 06:42
> @saschagrunert would the upstream seccomp work fix this issue? i.e: are we targeting a non-empty default profile for 1.19 or 1.20?

Not right now. I don't think that the CRI will change without preserving the backwards compatibility: https://github.com/kubernetes/cri-api/blob/1eae59a7c4dee45a900f54ea2502edff7e57fd68/pkg/apis/runtime/v1alpha2/api.proto#L287

I suggest that we close this issue.

**Comment by haircommander** [comment] 2020-11-18 16:22
users can override the empty profile behavior by configuring `seccomp_use_default_when_empty` in 1.20 https://github.com/cri-o/cri-o/pull/4212

**Closed by haircommander** 2020-11-18 16:22 UTC
Labels: CRI change
